name: "adinsights"
version: "1.0"
config-version: 2
profile: "adinsights"

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]

models:
  adinsights:
    staging:
      materialized: view
    marts:
      +materialized: incremental
      facts:
        materialized: incremental
        incremental_strategy: merge
        unique_key: ['date_day', 'campaign_id', 'ad_account_id']
      dimensions:
        materialized: table
    reference:
      materialized: table

seeds:
  adinsights:
    +quote_columns: false
    raw:
      +schema: raw
      +quote_columns: true
      google_ads_insights:
        +column_types:
          customer_id: text
          campaign_id: text
          ad_group_id: text
          criterion_id: text
          date_day: date
          geo_target_region: text
          cost_micros: numeric
          impressions: numeric
          clicks: numeric
          conversions: numeric
          _airbyte_emitted_at: timestamp
          _airbyte_raw_id: text
      meta_ads_insights:
        +column_types:
          ad_account_id: text
          campaign_id: text
          adset_id: text
          ad_id: text
          date_start: date
          region: text
          spend: numeric
          impressions: numeric
          clicks: numeric
          conversions: numeric
          updated_time: timestamp
          _airbyte_emitted_at: timestamp
          _airbyte_raw_id: text
    raw_google_ads:
      +schema: raw_google_ads
      +quote_columns: true
      campaign_daily:
        +column_types:
          customer_id: text
          campaign_id: text
          ad_group_id: text
          ad_id: text
          segments_date: date
          metrics_impressions: numeric
          metrics_clicks: numeric
          metrics_conversions: numeric
          metrics_conversions_value: numeric
          metrics_cost_micros: numeric
          metrics_average_cpc: numeric
          metrics_average_cpm: numeric
      geographic_view:
        +column_types:
          customer_id: text
          segments_date: date
          geo_target_id: text
          geo_target_country: text
          geo_target_state: text
          geo_target_city_name: text
          metrics_impressions: numeric
          metrics_clicks: numeric
          metrics_cost_micros: numeric
    raw_meta:
      +schema: raw_meta
      +quote_columns: true
      ad_insights:
        +column_types:
          account_id: text
          campaign_id: text
          adset_id: text
          ad_id: text
          date_start: date
          country: text
          region: text
          city: text
          impressions: numeric
          clicks: numeric
          spend: numeric
          cpc: numeric
          cpm: numeric
          ctr: numeric
          actions: text
      campaigns:
        +column_types:
          id: text
          account_id: text
          name: text
          status: text
          effective_status: text
          objective: text
          created_time: timestamp
          updated_time: timestamp
      ads:
        +column_types:
          id: text
          adset_id: text
          campaign_id: text
          account_id: text
          name: text
          status: text
          created_time: timestamp
          updated_time: timestamp
      adsets:
        +column_types:
          id: text
          campaign_id: text
          account_id: text
          name: text
          status: text
          daily_budget: numeric
          created_time: timestamp
          updated_time: timestamp
    geo_parish_lookup:
      +delimiter: ","
      +quote_columns: true
      +column_types:
        region_name: text
        parish_name: text
        parish_code: text
        latitude: numeric
        longitude: numeric
