name: 'adinsights'
version: '1.0'
config-version: 2
profile: 'adinsights'

model-paths: ['models']
seed-paths: ['seeds']
snapshot-paths: ['snapshots']
macro-paths: ['macros']

on-run-start:
  - '{{ apply_ci_fixtures() }}'

models:
  adinsights:
    staging:
      +materialized: view
    marts:
      +materialized: incremental
    reference:
      +materialized: table

snapshots:
  adinsights:
    +target_schema: "{{ var('snapshot_schema', target.schema) }}"

seeds:
  adinsights:
    +quote_columns: false
    demo:
      +schema: demo
      +quote_columns: false
      dim_tenants:
        +column_types:
          tenant_id: text
          tenant_name: text
          currency: text
          timezone: text
          snapshot_generated_at: timestamp
      dim_campaigns:
        +column_types:
          tenant_id: text
          campaign_id: text
          channel: text
          campaign_name: text
          objective: text
          status: text
          start_date: date
          end_date: date
          parish: text
      dim_creatives:
        +column_types:
          tenant_id: text
          campaign_id: text
          channel: text
          creative_id: text
          creative_name: text
          creative_type: text
      fact_daily_campaign_metrics:
        +column_types:
          date: date
          tenant_id: text
          channel: text
          campaign_id: text
          spend: numeric
          impressions: integer
          clicks: integer
          conversions: integer
          revenue: numeric
          roas: numeric
          snapshot_generated_at: timestamp
      fact_daily_parish_metrics:
        +column_types:
          date: date
          tenant_id: text
          channel: text
          parish: text
          spend: numeric
          impressions: integer
          clicks: integer
          conversions: integer
          revenue: numeric
          roas: numeric
      fact_daily_creative_metrics:
        +column_types:
          date: date
          tenant_id: text
          channel: text
          campaign_id: text
          creative_id: text
          creative_type: text
          spend: numeric
          impressions: integer
          clicks: integer
          conversions: integer
          revenue: numeric
          roas: numeric
      plan_monthly_budgets:
        +column_types:
          month: date
          tenant_id: text
          channel: text
          campaign_id: text
          planned_budget: numeric
    raw:
      +schema: raw
      +quote_columns: true
      google_ads_insights:
        +column_types:
          customer_id: text
          campaign_id: text
          campaign_name: text
          ad_group_id: text
          ad_name: text
          criterion_id: text
          date_day: date
          geo_target_region: text
          cost_micros: numeric
          impressions: numeric
          clicks: numeric
          conversions: numeric
          _airbyte_emitted_at: timestamp
          _airbyte_raw_id: text
      linkedin_transparency:
        +column_types:
          account_id: text
          campaign_id: text
          ad_creative_id: text
          activity_date: date
          region: text
          impressions: numeric
          clicks: numeric
          spend: numeric
          _airbyte_emitted_at: timestamp
      tiktok_transparency:
        +column_types:
          advertiser_id: text
          campaign_id: text
          ad_group_id: text
          ad_creative_id: text
          report_date: date
          region: text
          impressions: numeric
          clicks: numeric
          spend: numeric
          _airbyte_emitted_at: timestamp
      meta_ads_insights:
        +column_types:
          ad_account_id: text
          campaign_id: text
          campaign_name: text
          adset_id: text
          ad_id: text
          ad_name: text
          date_start: date
          region: text
          spend: numeric
          impressions: numeric
          clicks: numeric
          conversions: numeric
          updated_time: timestamp
          _airbyte_emitted_at: timestamp
          _airbyte_raw_id: text
    raw_google_ads:
      +schema: raw_google_ads
      +quote_columns: true
      campaign_daily:
        +column_types:
          customer_id: text
          campaign_id: text
          ad_group_id: text
          ad_id: text
          segments_date: date
          metrics_impressions: numeric
          metrics_clicks: numeric
          metrics_conversions: numeric
          metrics_conversions_value: numeric
          metrics_cost_micros: numeric
          metrics_average_cpc: numeric
          metrics_average_cpm: numeric
      geographic_view:
        +column_types:
          customer_id: text
          segments_date: date
          geo_target_id: text
          geo_target_country: text
          geo_target_state: text
          geo_target_city_name: text
          metrics_impressions: numeric
          metrics_clicks: numeric
          metrics_cost_micros: numeric
    raw_meta:
      +schema: raw_meta
      +quote_columns: true
      ad_insights:
        +column_types:
          account_id: text
          campaign_id: text
          adset_id: text
          ad_id: text
          date_start: date
          country: text
          region: text
          city: text
          impressions: numeric
          clicks: numeric
          spend: numeric
          cpc: numeric
          cpm: numeric
          ctr: numeric
          actions: text
      campaigns:
        +column_types:
          id: text
          account_id: text
          name: text
          status: text
          effective_status: text
          objective: text
          created_time: timestamp
          updated_time: timestamp
      ads:
        +column_types:
          id: text
          adset_id: text
          campaign_id: text
          account_id: text
          name: text
          status: text
          created_time: timestamp
          updated_time: timestamp
      adsets:
        +column_types:
          id: text
          campaign_id: text
          account_id: text
          name: text
          status: text
          daily_budget: numeric
          created_time: timestamp
          updated_time: timestamp
    geo_parish_lookup:
      +delimiter: ','
      +quote_columns: true
      +column_types:
        region_name: text
        parish_name: text
        parish_code: text
        latitude: numeric
        longitude: numeric
    raw__google_ads_insights:
      +quote_columns: true
      +column_types:
        customer_id: text
        campaign_id: text
        campaign_name: text
        ad_group_id: text
        ad_name: text
        criterion_id: text
        date_day: date
        geo_target_region: text
        cost_micros: numeric
        impressions: numeric
        clicks: numeric
        conversions: numeric
        _airbyte_emitted_at: timestamp
        _airbyte_raw_id: text
    raw__meta_ads_insights:
      +quote_columns: true
      +column_types:
        ad_account_id: text
        campaign_id: text
        campaign_name: text
        adset_id: text
        ad_id: text
        ad_name: text
        date_start: date
        region: text
        spend: numeric
        impressions: numeric
        clicks: numeric
        conversions: numeric
        updated_time: timestamp
        _airbyte_emitted_at: timestamp
        _airbyte_raw_id: text
    raw__linkedin_transparency:
      +quote_columns: true
      +column_types:
        account_id: text
        campaign_id: text
        ad_creative_id: text
        activity_date: date
        region: text
        impressions: numeric
        clicks: numeric
        spend: numeric
        _airbyte_emitted_at: timestamp
    raw__tiktok_transparency:
      +quote_columns: true
      +column_types:
        advertiser_id: text
        campaign_id: text
        ad_group_id: text
        ad_creative_id: text
        report_date: date
        region: text
        impressions: numeric
        clicks: numeric
        spend: numeric
        _airbyte_emitted_at: timestamp
    raw_google_ads__campaign_daily:
      +quote_columns: true
      +column_types:
        customer_id: text
        campaign_id: text
        ad_group_id: text
        ad_id: text
        segments_date: date
        metrics_impressions: numeric
        metrics_clicks: numeric
        metrics_conversions: numeric
        metrics_conversions_value: numeric
        metrics_cost_micros: numeric
        metrics_average_cpc: numeric
        metrics_average_cpm: numeric
    raw_google_ads__geographic_view:
      +quote_columns: true
      +column_types:
        customer_id: text
        segments_date: date
        geo_target_id: text
        geo_target_country: text
        geo_target_state: text
        geo_target_city_name: text
        metrics_impressions: numeric
        metrics_clicks: numeric
        metrics_cost_micros: numeric
    raw_meta__ad_insights:
      +quote_columns: true
      +column_types:
        account_id: text
        campaign_id: text
        adset_id: text
        ad_id: text
        date_start: date
        country: text
        region: text
        city: text
        impressions: numeric
        clicks: numeric
        spend: numeric
        cpc: numeric
        cpm: numeric
        ctr: numeric
        actions: text
    raw_meta__ads:
      +quote_columns: true
      +column_types:
        id: text
        adset_id: text
        campaign_id: text
        account_id: text
        name: text
        status: text
        created_time: timestamp
        updated_time: timestamp
    raw_meta__adsets:
      +quote_columns: true
      +column_types:
        id: text
        campaign_id: text
        account_id: text
        name: text
        status: text
        daily_budget: numeric
        created_time: timestamp
        updated_time: timestamp
    raw_meta__campaigns:
      +quote_columns: true
      +column_types:
        id: text
        account_id: text
        name: text
        status: text
        effective_status: text
        objective: text
        created_time: timestamp
        updated_time: timestamp
