name: "adinsights"
version: "1.0"
config-version: 2
profile: "adinsights"

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  adinsights:
    staging:
      materialized: view
    marts:
      +materialized: incremental
      facts:
        materialized: incremental
        incremental_strategy: merge
        unique_key: ['date_day', 'campaign_id', 'ad_account_id']
      dimensions:
        materialized: table
    reference:
      materialized: table

seeds:
  adinsights:
    +quote_columns: false
    geo_parish_lookup:
      +delimiter: ","
      +quote_columns: true
      +column_types:
        region_name: text
        parish_name: text
        parish_code: text
        latitude: numeric
        longitude: numeric
