# Generated by Django 5.1.13 on 2025-10-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_passwordresettoken"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="passwordresettoken",
            new_name="accounts_pa_user_id_e5b29b_idx",
            old_name="accounts_pa_user_id_b7d7a8_idx",
        ),
    ]
