# Generated by Django 5.1.14 on 2026-03-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_rename_accounts_pa_user_id_b7d7a8_idx_accounts_pa_user_id_e5b29b_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Admin"),
                    ("SM_ADMIN", "Admin (Portfolio Ops Lead)"),
                    ("SM_SUPPORT", "Support (Time-boxed)"),
                    ("SM_CONFIG_ADMIN", "White-label Configuration Admin"),
                    ("SM_ENTITLEMENTS", "Entitlements Manager"),
                    ("AGENCY_OWNER", "Agency Owner"),
                    ("AGENCY_ADMIN", "Agency Admin (Delegated)"),
                    ("AGENCY_TEAM_LEAD", "Agency Team Lead"),
                    ("AGENCY_SENIOR_ANALYST", "Agency Senior Analyst"),
                    ("AGENCY_ANALYST", "Agency Analyst (Jr)"),
                    ("CLIENT_TEAM_LEAD", "Client Team Lead (Tenant Admin)"),
                    ("CLIENT_SENIOR_LEAD", "Client Senior Lead"),
                    ("CLIENT_JUNIOR", "Client Junior"),
                    ("EXECUTIVE_VIEW", "Executive View"),
                    ("NON_EXECUTIVE_VIEW", "Non-Executive View"),
                    ("ADMIN", "Admin"),
                    ("ANALYST", "Analyst"),
                    ("VIEWER", "Viewer"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
    ]
