# Generated by Django 5.0.6 on 2025-10-13 02:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlertRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rule_slug", models.CharField(db_index=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("success", "Success"),
                            ("no_results", "No results"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("llm_summary", models.TextField(blank=True)),
                ("raw_results", models.JSONField(blank=True, default=list)),
                ("error_message", models.TextField(blank=True)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["rule_slug", "-created_at"], name="alerts_rule_ts"
                    )
                ],
            },
        ),
    ]
