FROM python:3.11-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
COPY pyproject.toml setup.cfg ./
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir .
COPY app ./app
CMD ["python", "-m", "app.worker"]
