# Generated by Django 5.1.13 on 2026-06-05 10:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0006_alter_role_name"),
        ("integrations", "0026_notificationchannel_secret_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentBrief",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("campaign_theme", models.CharField(blank=True, max_length=255)),
                ("audience", models.TextField(blank=True)),
                ("offer", models.TextField(blank=True)),
                ("tone", models.CharField(blank=True, max_length=128)),
                ("required_terms", models.JSONField(blank=True, default=list)),
                ("blocked_terms", models.JSONField(blank=True, default=list)),
                ("landing_url", models.URLField(blank=True)),
                ("date_start", models.DateField(blank=True, null=True)),
                ("date_end", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ContentDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("internal_review", "Internal review"),
                            (
                                "internal_changes_requested",
                                "Internal changes requested",
                            ),
                            ("internal_approved", "Internal approved"),
                            ("client_review", "Client review"),
                            ("client_changes_requested", "Client changes requested"),
                            ("client_approved", "Client approved"),
                            ("scheduled", "Scheduled"),
                            ("publishing", "Publishing"),
                            ("published", "Published"),
                            ("partially_published", "Partially published"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=40,
                    ),
                ),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "brief",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drafts",
                        to="content_ops.contentbrief",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_content_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_content_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_content_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="ContentDraftVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version_number", models.PositiveIntegerField()),
                ("caption", models.TextField(blank=True)),
                ("platform_overrides", models.JSONField(blank=True, default=dict)),
                ("change_note", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_draft_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="content_ops.contentdraft",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("draft_id", "version_number"),
            },
        ),
        migrations.AddField(
            model_name="contentdraft",
            name="active_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="content_ops.contentdraftversion",
            ),
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewer_type",
                    models.CharField(
                        choices=[("internal", "Internal"), ("client", "Client")],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_requested", "Not requested"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("changes_requested", "Changes requested"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("superseded", "Superseded"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("superseded_reason", models.CharField(blank=True, max_length=128)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_content_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="content_ops.contentdraft",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="content_ops.contentdraftversion",
                    ),
                ),
            ],
            options={
                "ordering": ("-requested_at",),
            },
        ),
        migrations.CreateModel(
            name="ContentSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_at", models.DateTimeField()),
                (
                    "timezone",
                    models.CharField(default="America/Jamaica", max_length=64),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("locked", "Locked"),
                            ("dispatching", "Dispatching"),
                            ("published", "Published"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=32,
                    ),
                ),
                ("approval_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="content_ops.contentdraft",
                    ),
                ),
                (
                    "scheduled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="content_ops.contentdraftversion",
                    ),
                ),
            ],
            options={
                "ordering": ("scheduled_at",),
            },
        ),
        migrations.CreateModel(
            name="ContentWorkspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("objective", models.TextField(blank=True)),
                ("brand_profile", models.JSONField(blank=True, default=dict)),
                ("target_channels", models.JSONField(blank=True, default=list)),
                (
                    "timezone",
                    models.CharField(default="America/Jamaica", max_length=64),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_workspaces",
                        to="integrations.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_content_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="contentdraft",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drafts",
                to="content_ops.contentworkspace",
            ),
        ),
        migrations.AddField(
            model_name="contentbrief",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="briefs",
                to="content_ops.contentworkspace",
            ),
        ),
        migrations.CreateModel(
            name="GenerationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("caption", "Caption"),
                            ("graphic_batch", "Graphic batch"),
                            ("variation", "Variation"),
                            ("resize", "Resize"),
                        ],
                        max_length=32,
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=64)),
                ("model_name", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("input_fingerprint", models.CharField(blank=True, max_length=128)),
                ("redacted_prompt_summary", models.TextField(blank=True)),
                ("prompt_policy_result", models.JSONField(blank=True, default=dict)),
                ("result_summary", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                (
                    "brief",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_jobs",
                        to="content_ops.contentbrief",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_generation_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_jobs",
                        to="content_ops.contentworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="contentdraftversion",
            name="source_generation_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="draft_versions",
                to="content_ops.generationjob",
            ),
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("ai_generated", "AI generated"),
                            ("imported", "Imported"),
                        ],
                        max_length=32,
                    ),
                ),
                ("storage_key", models.CharField(max_length=512)),
                ("mime_type", models.CharField(max_length=128)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("alt_text", models.TextField(blank=True)),
                ("renditions", models.JSONField(blank=True, default=dict)),
                ("ai_lineage", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("quarantined", "Quarantined"),
                            ("deleted", "Deleted"),
                        ],
                        default="available",
                        max_length=32,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_assets",
                        to="content_ops.contentworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="contentdraftversion",
            name="media_assets",
            field=models.ManyToManyField(
                blank=True, related_name="draft_versions", to="content_ops.mediaasset"
            ),
        ),
        migrations.CreateModel(
            name="PublishedPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("facebook_page", "Facebook Page"),
                            ("instagram", "Instagram"),
                        ],
                        max_length=32,
                    ),
                ),
                ("meta_post_id", models.CharField(max_length=128)),
                ("permalink", models.URLField(blank=True)),
                ("published_at", models.DateTimeField()),
                (
                    "reporting_link_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("linked", "Linked"),
                            ("unavailable", "Unavailable"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "last_metrics_refresh_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_posts",
                        to="content_ops.contentdraft",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_posts",
                        to="content_ops.contentdraftversion",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_posts",
                        to="content_ops.contentworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-published_at",),
            },
        ),
        migrations.CreateModel(
            name="OrganicPostMetricSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metric_date", models.DateField()),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("facebook_page", "Facebook Page"),
                            ("instagram", "Instagram"),
                        ],
                        max_length=32,
                    ),
                ),
                ("impressions", models.BigIntegerField(default=0)),
                ("reach", models.BigIntegerField(default=0)),
                ("engagements", models.BigIntegerField(default=0)),
                ("clicks", models.BigIntegerField(default=0)),
                ("saves", models.BigIntegerField(default=0)),
                ("shares", models.BigIntegerField(default=0)),
                ("video_views", models.BigIntegerField(default=0)),
                ("source", models.CharField(max_length=64)),
                ("fetched_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "published_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_snapshots",
                        to="content_ops.publishedpost",
                    ),
                ),
            ],
            options={
                "ordering": ("-metric_date",),
            },
        ),
        migrations.CreateModel(
            name="PublishingIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook_page", "Facebook Page"),
                            ("instagram", "Instagram"),
                        ],
                        max_length=32,
                    ),
                ),
                ("meta_page_id", models.CharField(blank=True, max_length=128)),
                ("ig_user_id", models.CharField(blank=True, max_length=128)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                (
                    "selection_state",
                    models.CharField(
                        choices=[
                            ("selected", "Selected"),
                            ("revoked", "Revoked"),
                            ("not_selected", "Not selected"),
                        ],
                        default="not_selected",
                        max_length=32,
                    ),
                ),
                (
                    "publish_readiness_state",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("ready", "Ready"),
                            ("blocked", "Blocked"),
                            ("needs_reauth", "Needs reauth"),
                            ("needs_review", "Needs review"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                (
                    "publish_readiness_reason",
                    models.CharField(blank=True, max_length=128),
                ),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "credential_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_publishing_identities",
                        to="integrations.platformcredential",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("display_name", "platform"),
            },
        ),
        migrations.AddField(
            model_name="publishedpost",
            name="publishing_identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_posts",
                to="content_ops.publishingidentity",
            ),
        ),
        migrations.CreateModel(
            name="PublishAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("facebook_page", "Facebook Page"),
                            ("instagram", "Instagram"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("preflight", "Preflight"),
                            ("blocked", "Blocked"),
                            ("container_creating", "Container creating"),
                            ("container_pending", "Container pending"),
                            ("container_ready", "Container ready"),
                            ("publishing", "Publishing"),
                            ("published", "Published"),
                            ("failed_retryable", "Failed retryable"),
                            ("failed_terminal", "Failed terminal"),
                            ("container_expired", "Container expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("correlation_id", models.CharField(blank=True, max_length=128)),
                ("meta_container_id", models.CharField(blank=True, max_length=128)),
                (
                    "meta_container_created_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("meta_post_id", models.CharField(blank=True, max_length=128)),
                ("failure_code", models.CharField(blank=True, max_length=128)),
                ("failure_detail_safe", models.TextField(blank=True)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publish_attempts",
                        to="content_ops.contentdraft",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publish_attempts",
                        to="content_ops.contentschedule",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publish_attempts",
                        to="content_ops.contentdraftversion",
                    ),
                ),
                (
                    "publishing_identity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publish_attempts",
                        to="content_ops.publishingidentity",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ApprovalDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("changes_requested", "Changes requested"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=32,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_approval_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_records",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "approval_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="content_ops.approvalrequest",
                    ),
                ),
            ],
            options={
                "ordering": ("-decided_at",),
                "indexes": [
                    models.Index(fields=["tenant", "decision"], name="content_decision")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["tenant", "status"], name="content_approval_status"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["tenant", "reviewer_type"], name="content_approval_type"
            ),
        ),
        migrations.AddIndex(
            model_name="contentschedule",
            index=models.Index(
                fields=["tenant", "state", "scheduled_at"], name="content_schedule_due"
            ),
        ),
        migrations.AddIndex(
            model_name="contentschedule",
            index=models.Index(
                fields=["tenant", "draft"], name="content_schedule_draft"
            ),
        ),
        migrations.AddIndex(
            model_name="contentworkspace",
            index=models.Index(
                fields=["tenant", "archived_at"], name="content_ws_archived"
            ),
        ),
        migrations.AddIndex(
            model_name="contentworkspace",
            index=models.Index(fields=["tenant", "client"], name="content_ws_client"),
        ),
        migrations.AddIndex(
            model_name="contentdraft",
            index=models.Index(fields=["tenant", "workspace"], name="content_draft_ws"),
        ),
        migrations.AddIndex(
            model_name="contentdraft",
            index=models.Index(fields=["tenant", "state"], name="content_draft_state"),
        ),
        migrations.AddIndex(
            model_name="contentbrief",
            index=models.Index(fields=["tenant", "workspace"], name="content_brief_ws"),
        ),
        migrations.AddIndex(
            model_name="contentbrief",
            index=models.Index(
                fields=["tenant", "status"], name="content_brief_status"
            ),
        ),
        migrations.AddIndex(
            model_name="generationjob",
            index=models.Index(fields=["tenant", "status"], name="content_gen_status"),
        ),
        migrations.AddIndex(
            model_name="generationjob",
            index=models.Index(fields=["tenant", "job_type"], name="content_gen_type"),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(fields=["tenant", "workspace"], name="content_asset_ws"),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["tenant", "status"], name="content_asset_status"
            ),
        ),
        migrations.AddIndex(
            model_name="contentdraftversion",
            index=models.Index(
                fields=["tenant", "draft"], name="content_version_draft"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contentdraftversion",
            unique_together={("tenant", "draft", "version_number")},
        ),
        migrations.AddIndex(
            model_name="organicpostmetricsnapshot",
            index=models.Index(
                fields=["tenant", "metric_date"], name="content_metric_date"
            ),
        ),
        migrations.AddIndex(
            model_name="organicpostmetricsnapshot",
            index=models.Index(
                fields=["tenant", "channel"], name="content_metric_channel"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organicpostmetricsnapshot",
            unique_together={
                ("tenant", "published_post", "metric_date", "channel", "source")
            },
        ),
        migrations.AddIndex(
            model_name="publishingidentity",
            index=models.Index(
                fields=["tenant", "platform"], name="content_ident_platform"
            ),
        ),
        migrations.AddIndex(
            model_name="publishingidentity",
            index=models.Index(
                fields=["tenant", "meta_page_id"], name="content_ident_page"
            ),
        ),
        migrations.AddIndex(
            model_name="publishingidentity",
            index=models.Index(
                fields=["tenant", "ig_user_id"], name="content_ident_ig"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="publishingidentity",
            unique_together={("tenant", "platform", "meta_page_id", "ig_user_id")},
        ),
        migrations.AddIndex(
            model_name="publishedpost",
            index=models.Index(
                fields=["tenant", "channel"], name="content_post_channel"
            ),
        ),
        migrations.AddIndex(
            model_name="publishedpost",
            index=models.Index(
                fields=["tenant", "published_at"], name="content_post_published"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="publishedpost",
            unique_together={("tenant", "channel", "meta_post_id")},
        ),
        migrations.AddIndex(
            model_name="publishattempt",
            index=models.Index(
                fields=["tenant", "state"], name="content_attempt_state"
            ),
        ),
        migrations.AddIndex(
            model_name="publishattempt",
            index=models.Index(
                fields=["tenant", "channel"], name="content_attempt_channel"
            ),
        ),
        migrations.AddIndex(
            model_name="publishattempt",
            index=models.Index(
                fields=["tenant", "next_retry_at"], name="content_attempt_retry"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="publishattempt",
            unique_together={("tenant", "idempotency_key")},
        ),
    ]
