# Generated by Django 5.1.13 on 2026-06-23 23:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_role_name"),
        ("content_ops", "0003_ai_usage_record"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionalAgentProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("caribbean", "Caribbean"),
                            ("peru_latam", "Peru / LATAM"),
                        ],
                        max_length=32,
                    ),
                ),
                ("locale", models.CharField(blank=True, max_length=16)),
                ("language", models.CharField(blank=True, max_length=64)),
                ("timezone", models.CharField(blank=True, max_length=64)),
                ("brand_voice", models.JSONField(blank=True, default=dict)),
                ("required_terms", models.JSONField(blank=True, default=list)),
                ("blocked_terms", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="is_approved_reference",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="reference_locale",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="reference_region",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["tenant", "is_approved_reference"], name="content_asset_ref"
            ),
        ),
        migrations.AddField(
            model_name="regionalagentprofile",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_regional_agents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="regionalagentprofile",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_records",
                to="accounts.tenant",
            ),
        ),
        migrations.AddField(
            model_name="regionalagentprofile",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regional_agents",
                to="content_ops.contentworkspace",
            ),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="regional_agent_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generation_jobs",
                to="content_ops.regionalagentprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="regionalagentprofile",
            index=models.Index(fields=["tenant", "workspace"], name="content_agent_ws"),
        ),
        migrations.AddIndex(
            model_name="regionalagentprofile",
            index=models.Index(
                fields=["tenant", "region"], name="content_agent_region"
            ),
        ),
    ]
