# Generated by Django 5.1.13 on 2026-06-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_ops", "0004_regional_agent_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiusagerecord",
            name="images",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
