# Generated by Django 5.1.13 on 2026-06-24 19:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_role_name"),
        ("content_ops", "0005_ai_usage_images"),
        ("integrations", "0026_notificationchannel_secret_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandKit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("workspace", "Workspace"),
                            ("client", "Client"),
                            ("post_type", "Post type"),
                        ],
                        default="workspace",
                        max_length=16,
                    ),
                ),
                ("post_type", models.CharField(blank=True, max_length=64)),
                ("standing_instructions", models.JSONField(blank=True, default=dict)),
                ("visual_config", models.JSONField(blank=True, default=dict)),
                ("required_terms", models.JSONField(blank=True, default=list)),
                ("blocked_terms", models.JSONField(blank=True, default=list)),
                (
                    "logo_placement",
                    models.CharField(
                        choices=[
                            ("top_left", "Top left"),
                            ("top_right", "Top right"),
                            ("bottom_left", "Bottom left"),
                            ("bottom_right", "Bottom right"),
                            ("center", "Center"),
                        ],
                        default="bottom_right",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="FooterPreset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("website", models.CharField(blank=True, max_length=255)),
                ("contact", models.CharField(blank=True, max_length=255)),
                ("handles", models.JSONField(blank=True, default=list)),
                ("tagline", models.CharField(blank=True, max_length=255)),
                ("background_hex", models.CharField(blank=True, max_length=7)),
                ("text_hex", models.CharField(blank=True, max_length=7)),
                (
                    "band_position",
                    models.CharField(
                        choices=[("bottom", "Bottom"), ("top", "Top")],
                        default="bottom",
                        max_length=8,
                    ),
                ),
                (
                    "band_height_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Band height as a fraction of canvas height (0–1).",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "separator",
                    models.CharField(blank=True, default=" • ", max_length=8),
                ),
                ("field_priority", models.JSONField(blank=True, default=list)),
                ("uppercase_primary", models.BooleanField(default=False)),
                ("locale", models.CharField(blank=True, max_length=16)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="MediaAssetCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("logo_library", "Logo library"),
                            ("reference_library", "Reference library"),
                        ],
                        default="general",
                        max_length=24,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("region", models.CharField(blank=True, max_length=32)),
                ("locale", models.CharField(blank=True, max_length=16)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="MediaAssetCollectionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ("collection_id", "order"),
            },
        ),
        migrations.CreateModel(
            name="MediaAssetTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=64)),
                ("slug", models.SlugField(max_length=64)),
            ],
            options={
                "ordering": ("label",),
            },
        ),
        migrations.CreateModel(
            name="MediaAssetTagAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="content_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="deliverable_group_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="file_size_bytes",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="kind",
            field=models.CharField(
                choices=[
                    ("content", "Content"),
                    ("logo", "Logo"),
                    ("reference", "Reference"),
                ],
                default="content",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="logo_variant",
            field=models.CharField(
                blank=True,
                choices=[
                    ("light", "Light (for dark backgrounds)"),
                    ("dark", "Dark (for light backgrounds)"),
                    ("full_color", "Full color"),
                    ("monochrome", "Monochrome"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="reference_descriptor",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="reference_role",
            field=models.CharField(
                blank=True,
                choices=[("style", "Style"), ("subject", "Subject"), ("mood", "Mood")],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="reference_weight",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="usage_rights_attested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="usage_rights_attested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="usage_rights_attested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_attested_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="usage_rights_note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["tenant", "kind", "status"], name="content_asset_kind"
            ),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["tenant", "content_hash"], name="content_asset_hash"
            ),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["tenant", "deliverable_group_id"], name="content_asset_group"
            ),
        ),
        migrations.AddField(
            model_name="brandkit",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_brand_kits",
                to="integrations.client",
            ),
        ),
        migrations.AddField(
            model_name="brandkit",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_brand_kits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="brandkit",
            name="default_logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_brand_kits",
                to="content_ops.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="brandkit",
            name="logo_dark",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="content_ops.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="brandkit",
            name="logo_light",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="content_ops.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="brandkit",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_records",
                to="accounts.tenant",
            ),
        ),
        migrations.AddField(
            model_name="brandkit",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brand_kits",
                to="content_ops.contentworkspace",
            ),
        ),
        migrations.AddField(
            model_name="footerpreset",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_footer_presets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="footerpreset",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_records",
                to="accounts.tenant",
            ),
        ),
        migrations.AddField(
            model_name="footerpreset",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="footer_presets",
                to="content_ops.contentworkspace",
            ),
        ),
        migrations.AddField(
            model_name="brandkit",
            name="default_footer_preset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="brand_kits",
                to="content_ops.footerpreset",
            ),
        ),
        migrations.AddField(
            model_name="mediaassetcollection",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_asset_collections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mediaassetcollection",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_records",
                to="accounts.tenant",
            ),
        ),
        migrations.AddField(
            model_name="mediaassetcollection",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_collections",
                to="content_ops.contentworkspace",
            ),
        ),
        migrations.AddField(
            model_name="mediaassetcollectionitem",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mediaassetcollectionitem",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_items",
                to="content_ops.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="mediaassetcollectionitem",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="content_ops.mediaassetcollection",
            ),
        ),
        migrations.AddField(
            model_name="mediaassetcollectionitem",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_records",
                to="accounts.tenant",
            ),
        ),
        migrations.AddField(
            model_name="mediaassetcollection",
            name="assets",
            field=models.ManyToManyField(
                blank=True,
                related_name="collections",
                through="content_ops.MediaAssetCollectionItem",
                to="content_ops.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="mediaassettag",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_records",
                to="accounts.tenant",
            ),
        ),
        migrations.AddField(
            model_name="mediaassettag",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_tags",
                to="content_ops.contentworkspace",
            ),
        ),
        migrations.AddField(
            model_name="mediaassettagassignment",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tag_assignments",
                to="content_ops.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="mediaassettagassignment",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="content_ops.mediaassettag",
            ),
        ),
        migrations.AddField(
            model_name="mediaassettagassignment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_records",
                to="accounts.tenant",
            ),
        ),
        migrations.AddField(
            model_name="mediaassettag",
            name="assets",
            field=models.ManyToManyField(
                blank=True,
                related_name="tags",
                through="content_ops.MediaAssetTagAssignment",
                to="content_ops.mediaasset",
            ),
        ),
        migrations.AddIndex(
            model_name="footerpreset",
            index=models.Index(
                fields=["tenant", "workspace", "is_active"], name="content_footer_ws"
            ),
        ),
        migrations.AddIndex(
            model_name="brandkit",
            index=models.Index(
                fields=["tenant", "workspace", "is_active"], name="content_brandkit_ws"
            ),
        ),
        migrations.AddIndex(
            model_name="brandkit",
            index=models.Index(
                fields=["tenant", "client"], name="content_brandkit_client"
            ),
        ),
        migrations.AddIndex(
            model_name="brandkit",
            index=models.Index(
                fields=["tenant", "scope", "post_type"], name="content_brandkit_scope"
            ),
        ),
        migrations.AddIndex(
            model_name="mediaassetcollectionitem",
            index=models.Index(
                fields=["tenant", "collection"], name="content_coll_item"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mediaassetcollectionitem",
            unique_together={("tenant", "collection", "asset")},
        ),
        migrations.AddIndex(
            model_name="mediaassetcollection",
            index=models.Index(
                fields=["tenant", "workspace", "purpose"], name="content_coll_ws"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mediaassetcollection",
            unique_together={("tenant", "workspace", "name")},
        ),
        migrations.AddIndex(
            model_name="mediaassettagassignment",
            index=models.Index(fields=["tenant", "asset"], name="content_tag_assign"),
        ),
        migrations.AlterUniqueTogether(
            name="mediaassettagassignment",
            unique_together={("tenant", "tag", "asset")},
        ),
        migrations.AddIndex(
            model_name="mediaassettag",
            index=models.Index(fields=["tenant", "slug"], name="content_tag_slug"),
        ),
        migrations.AlterUniqueTogether(
            name="mediaassettag",
            unique_together={("tenant", "workspace", "slug")},
        ),
    ]
