# Generated by Django 5.1.13 on 2026-06-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ops', '0006_asset_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentworkspace',
            name='quick_post_approval_mode',
            field=models.CharField(choices=[('required', 'Require approval before publishing'), ('bypass', 'Allow publishers to post without approval')], default='bypass', max_length=16),
        ),
    ]
