# Generated by Django 5.0.6 on 2025-10-12 07:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("META", "Meta"),
                            ("GOOGLE", "Google Ads"),
                            ("LINKEDIN", "LinkedIn"),
                            ("TIKTOK", "TikTok"),
                        ],
                        max_length=16,
                    ),
                ),
                ("account_id", models.CharField(max_length=128)),
                ("access_token_enc", models.BinaryField()),
                ("access_token_nonce", models.BinaryField()),
                ("access_token_tag", models.BinaryField()),
                ("refresh_token_enc", models.BinaryField(blank=True, null=True)),
                ("refresh_token_nonce", models.BinaryField(blank=True, null=True)),
                ("refresh_token_tag", models.BinaryField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("dek_key_version", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_credentials",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "unique_together": {("tenant", "provider", "account_id")},
            },
        ),
    ]
