# Generated by Django 5.0.6 on 2025-10-13 00:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_invitation"),
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AirbyteConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("connection_id", models.UUIDField()),
                ("workspace_id", models.UUIDField(blank=True, null=True)),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("interval", "Interval"),
                            ("cron", "Cron"),
                        ],
                        default="interval",
                        max_length=16,
                    ),
                ),
                (
                    "interval_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("cron_expression", models.CharField(blank=True, max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_job_id", models.CharField(blank=True, max_length=64)),
                ("last_job_status", models.CharField(blank=True, max_length=32)),
                ("last_job_created_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="airbyte_connections",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["tenant", "name"],
                "unique_together": {("tenant", "connection_id")},
            },
        ),
    ]
