# Generated by Django 5.0.6 on 2025-10-13 06:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_invitation"),
        ("integrations", "0003_tenantairbytesyncstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRuleDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("metric", models.CharField(max_length=64)),
                (
                    "comparison_operator",
                    models.CharField(
                        choices=[
                            ("gt", "greater_than"),
                            ("gte", "greater_than_equal"),
                            ("lt", "less_than"),
                            ("lte", "less_than_equal"),
                        ],
                        default="gt",
                        max_length=3,
                    ),
                ),
                ("threshold", models.DecimalField(decimal_places=2, max_digits=12)),
                ("lookback_hours", models.PositiveIntegerField(default=24)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                        ],
                        default="medium",
                        max_length=6,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rule_definitions",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "unique_together": {("tenant", "name")},
            },
        ),
        migrations.CreateModel(
            name="CampaignBudget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "monthly_target",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("currency", models.CharField(max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_budgets",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "unique_together": {("tenant", "name")},
            },
        ),
    ]
