# Generated by Django 5.0.6 on 2025-10-13 20:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_invitation"),
        ("integrations", "0005_airbyteconnection_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="AirbyteJobTelemetry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_id", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=32)),
                ("started_at", models.DateTimeField()),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("records_synced", models.BigIntegerField(blank=True, null=True)),
                ("bytes_synced", models.BigIntegerField(blank=True, null=True)),
                (
                    "api_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_telemetry",
                        to="integrations.airbyteconnection",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="airbyte_job_telemetry",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at", "-created_at"),
                "unique_together": {("connection", "job_id")},
            },
        ),
    ]
