# Generated by Django 5.1.14 on 2026-02-17 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_rename_accounts_pa_user_id_b7d7a8_idx_accounts_pa_user_id_e5b29b_idx",
        ),
        ("integrations", "0007_airbyteconnection_syncmetadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformcredential",
            name="auth_mode",
            field=models.CharField(
                choices=[("user_oauth", "User OAuth"), ("system_user", "System User")],
                default="user_oauth",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="platformcredential",
            name="declined_scopes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="platformcredential",
            name="granted_scopes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="platformcredential",
            name="issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="platformcredential",
            name="last_refresh_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="platformcredential",
            name="last_refreshed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="platformcredential",
            name="last_validated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="platformcredential",
            name="token_status",
            field=models.CharField(
                choices=[
                    ("valid", "Valid"),
                    ("expiring", "Expiring"),
                    ("invalid", "Invalid"),
                    ("reauth_required", "Reauth Required"),
                ],
                default="valid",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="platformcredential",
            name="token_status_reason",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="MetaAccountSyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.CharField(max_length=128)),
                ("last_job_id", models.CharField(blank=True, max_length=64)),
                ("last_job_status", models.CharField(blank=True, max_length=32)),
                ("last_job_error", models.TextField(blank=True)),
                ("last_sync_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_window_start", models.DateField(blank=True, null=True)),
                ("last_window_end", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meta_account_sync_states",
                        to="integrations.airbyteconnection",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_account_sync_states",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("tenant", "account_id"),
                "unique_together": {("tenant", "account_id")},
            },
        ),
    ]
