# Generated by Django 5.1.14 on 2026-02-19 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_rename_accounts_pa_user_id_b7d7a8_idx_accounts_pa_user_id_e5b29b_idx",
        ),
        ("integrations", "0008_platformcredential_auth_mode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("META", "Meta"),
                            ("GOOGLE", "Google Ads"),
                            ("LINKEDIN", "LinkedIn"),
                            ("TIKTOK", "TikTok"),
                        ],
                        default="META",
                        max_length=16,
                    ),
                ),
                ("endpoint", models.CharField(blank=True, max_length=255)),
                ("account_id", models.CharField(blank=True, max_length=128)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_subcode", models.CharField(blank=True, max_length=64)),
                ("message", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("correlation_id", models.CharField(blank=True, max_length=128)),
                ("is_retryable", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_error_logs",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="apierrorlog",
            index=models.Index(
                fields=["tenant", "provider", "created_at"],
                name="apierr_tenant_provider_ts",
            ),
        ),
        migrations.AddIndex(
            model_name="apierrorlog",
            index=models.Index(
                fields=["tenant", "account_id"],
                name="apierr_tenant_account",
            ),
        ),
    ]
