# Generated by Django 5.1.14 on 2026-02-19 20:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


DEFAULT_METRICS = [
    {
        "metric_key": "page_post_engagements",
        "level": "PAGE",
        "supported_periods": ["day", "week", "days_28"],
        "supports_breakdowns": [],
        "status": "ACTIVE",
        "replacement_metric_key": "",
        "is_default": True,
    },
    {
        "metric_key": "page_total_actions",
        "level": "PAGE",
        "supported_periods": ["day", "week", "days_28"],
        "supports_breakdowns": [],
        "status": "ACTIVE",
        "replacement_metric_key": "",
        "is_default": True,
    },
    {
        "metric_key": "page_daily_follows_unique",
        "level": "PAGE",
        "supported_periods": ["day", "week", "days_28"],
        "supports_breakdowns": [],
        "status": "ACTIVE",
        "replacement_metric_key": "",
        "is_default": True,
    },
    {
        "metric_key": "page_impressions_unique",
        "level": "PAGE",
        "supported_periods": ["day", "week", "days_28"],
        "supports_breakdowns": [],
        "status": "ACTIVE",
        "replacement_metric_key": "page_views_total",
        "is_default": True,
    },
    {
        "metric_key": "page_views_total",
        "level": "PAGE",
        "supported_periods": ["day", "week", "days_28"],
        "supports_breakdowns": [],
        "status": "UNKNOWN",
        "replacement_metric_key": "",
        "is_default": False,
    },
    {
        "metric_key": "post_reactions_like_total",
        "level": "POST",
        "supported_periods": ["lifetime"],
        "supports_breakdowns": [],
        "status": "ACTIVE",
        "replacement_metric_key": "",
        "is_default": True,
    },
    {
        "metric_key": "post_reactions_love_total",
        "level": "POST",
        "supported_periods": ["lifetime"],
        "supports_breakdowns": [],
        "status": "ACTIVE",
        "replacement_metric_key": "",
        "is_default": True,
    },
    {
        "metric_key": "post_reactions_wow_total",
        "level": "POST",
        "supported_periods": ["lifetime"],
        "supports_breakdowns": [],
        "status": "ACTIVE",
        "replacement_metric_key": "",
        "is_default": True,
    },
    {
        "metric_key": "post_impressions",
        "level": "POST",
        "supported_periods": ["lifetime"],
        "supports_breakdowns": [],
        "status": "ACTIVE",
        "replacement_metric_key": "",
        "is_default": True,
    },
    {
        "metric_key": "post_impressions_unique",
        "level": "POST",
        "supported_periods": ["lifetime"],
        "supports_breakdowns": [],
        "status": "UNKNOWN",
        "replacement_metric_key": "post_impressions",
        "is_default": True,
    },
    {
        "metric_key": "post_media_view",
        "level": "POST",
        "supported_periods": ["lifetime"],
        "supports_breakdowns": ["is_from_ads", "is_from_followers"],
        "status": "UNKNOWN",
        "replacement_metric_key": "",
        "is_default": True,
    },
]


def seed_metric_registry(apps, schema_editor):  # noqa: ARG001
    MetaMetricRegistry = apps.get_model("integrations", "MetaMetricRegistry")
    for metric in DEFAULT_METRICS:
        MetaMetricRegistry.objects.update_or_create(
            metric_key=metric["metric_key"],
            level=metric["level"],
            defaults={
                "supported_periods": metric["supported_periods"],
                "supports_breakdowns": metric["supports_breakdowns"],
                "status": metric["status"],
                "replacement_metric_key": metric["replacement_metric_key"],
                "is_default": metric["is_default"],
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_rename_accounts_pa_user_id_b7d7a8_idx_accounts_pa_user_id_e5b29b_idx",
        ),
        ("integrations", "0009_apierrorlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("app_scoped_user_id", models.CharField(blank=True, max_length=128)),
                ("token_enc", models.BinaryField()),
                ("token_nonce", models.BinaryField()),
                ("token_tag", models.BinaryField()),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("dek_key_version", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_connections",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MetaMetricRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_key", models.CharField(max_length=191)),
                (
                    "level",
                    models.CharField(
                        choices=[("PAGE", "Page"), ("POST", "Post")], max_length=8
                    ),
                ),
                ("supported_periods", models.JSONField(blank=True, default=list)),
                ("supports_breakdowns", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DEPRECATED", "Deprecated"),
                            ("INVALID", "Invalid"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                (
                    "replacement_metric_key",
                    models.CharField(blank=True, max_length=191),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["level", "status"], name="meta_metric_level_status"
                    )
                ],
                "unique_together": {("metric_key", "level")},
            },
        ),
        migrations.CreateModel(
            name="MetaPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_id", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=255)),
                ("page_token_enc", models.BinaryField()),
                ("page_token_nonce", models.BinaryField()),
                ("page_token_tag", models.BinaryField()),
                ("page_token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("can_analyze", models.BooleanField(default=False)),
                ("tasks", models.JSONField(blank=True, default=list)),
                ("perms", models.JSONField(blank=True, default=list)),
                ("is_default", models.BooleanField(default=False)),
                ("dek_key_version", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pages",
                        to="integrations.metaconnection",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_pages",
                        to="accounts.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MetaInsightPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_key", models.CharField(max_length=191)),
                ("period", models.CharField(max_length=32)),
                ("end_time", models.DateTimeField()),
                (
                    "value_num",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                ("value_json", models.JSONField(blank=True, null=True)),
                (
                    "breakdown_key",
                    models.CharField(blank=True, max_length=191, null=True),
                ),
                (
                    "breakdown_key_normalized",
                    models.CharField(default="", max_length=191),
                ),
                ("breakdown_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_insight_points",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insight_points",
                        to="integrations.metapage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MetaPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.CharField(max_length=191)),
                ("message", models.TextField(blank=True)),
                ("permalink_url", models.URLField(blank=True, max_length=500)),
                ("created_time", models.DateTimeField(blank=True, null=True)),
                ("updated_time", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="integrations.metapage",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_posts",
                        to="accounts.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MetaPostInsightPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_key", models.CharField(max_length=191)),
                ("period", models.CharField(max_length=32)),
                ("end_time", models.DateTimeField()),
                (
                    "value_num",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                ("value_json", models.JSONField(blank=True, null=True)),
                (
                    "breakdown_key",
                    models.CharField(blank=True, max_length=191, null=True),
                ),
                (
                    "breakdown_key_normalized",
                    models.CharField(default="", max_length=191),
                ),
                ("breakdown_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insight_points",
                        to="integrations.metapost",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_post_insight_points",
                        to="accounts.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="metaconnection",
            index=models.Index(
                fields=["tenant", "is_active"], name="meta_conn_tenant_active"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="metaconnection",
            unique_together={("tenant", "user", "app_scoped_user_id")},
        ),
        migrations.AddIndex(
            model_name="metapage",
            index=models.Index(
                fields=["tenant", "is_default"], name="meta_page_tenant_default"
            ),
        ),
        migrations.AddConstraint(
            model_name="metapage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("tenant",),
                name="meta_page_single_default_per_tenant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="metapage",
            unique_together={("tenant", "page_id")},
        ),
        migrations.AddIndex(
            model_name="metainsightpoint",
            index=models.Index(
                fields=["page", "metric_key", "period", "end_time"],
                name="meta_page_metric_period_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="metainsightpoint",
            constraint=models.UniqueConstraint(
                fields=(
                    "tenant",
                    "page",
                    "metric_key",
                    "period",
                    "end_time",
                    "breakdown_key_normalized",
                ),
                name="meta_page_insight_point_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="metapost",
            index=models.Index(
                fields=["page", "created_time"], name="meta_post_page_created"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="metapost",
            unique_together={("tenant", "page", "post_id")},
        ),
        migrations.AddIndex(
            model_name="metapostinsightpoint",
            index=models.Index(
                fields=["post", "metric_key", "period", "end_time"],
                name="meta_post_metric_period_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="metapostinsightpoint",
            constraint=models.UniqueConstraint(
                fields=(
                    "tenant",
                    "post",
                    "metric_key",
                    "period",
                    "end_time",
                    "breakdown_key_normalized",
                ),
                name="meta_post_insight_point_unique",
            ),
        ),
        migrations.RunPython(seed_metric_registry, migrations.RunPython.noop),
    ]
