# Generated by Django 5.1.14 on 2026-02-19 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_rename_accounts_pa_user_id_b7d7a8_idx_accounts_pa_user_id_e5b29b_idx"),
        ("integrations", "0010_meta_page_post_insights"),
    ]

    operations = [
        migrations.AddField(
            model_name="metapage",
            name="category",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="metapage",
            name="last_posts_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metapage",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metapost",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metapost",
            name="media_type",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name="MetaMetricSupportStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("PAGE", "Page"), ("POST", "Post")],
                        max_length=8,
                    ),
                ),
                ("metric_key", models.CharField(max_length=191)),
                ("supported", models.BooleanField(default=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_support_statuses",
                        to="integrations.metapage",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_metric_support_statuses",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "unique_together": {("tenant", "page", "level", "metric_key")},
            },
        ),
        migrations.AddIndex(
            model_name="metametricsupportstatus",
            index=models.Index(
                fields=["page", "level", "supported"],
                name="meta_support_page_level_sup",
            ),
        ),
        migrations.AddIndex(
            model_name="metametricsupportstatus",
            index=models.Index(
                fields=["tenant", "level"],
                name="meta_support_tenant_level",
            ),
        ),
    ]
