# Generated by Django 5.1.14 on 2026-02-19 23:10

from __future__ import annotations

import json
from pathlib import Path

from django.db import migrations


def sync_metric_registry_catalog(apps, schema_editor):  # noqa: ARG001
    MetaMetricRegistry = apps.get_model("integrations", "MetaMetricRegistry")
    catalog_path = Path(__file__).resolve().parents[1] / "data" / "meta_metric_catalog.json"
    catalog = json.loads(catalog_path.read_text())
    if not isinstance(catalog, list):
        return

    for definition in catalog:
        if not isinstance(definition, dict):
            continue
        metric_key = str(definition.get("metric_key", "")).strip()
        level = str(definition.get("level", "")).strip()
        if not metric_key or not level:
            continue
        metadata = {}
        deprecated_on = str(definition.get("deprecated_on", "")).strip()
        if deprecated_on:
            metadata["deprecated_on"] = deprecated_on
        MetaMetricRegistry.objects.update_or_create(
            metric_key=metric_key,
            level=level,
            defaults={
                "supported_periods": list(definition.get("supported_periods") or []),
                "supports_breakdowns": list(definition.get("supports_breakdowns") or []),
                "status": str(definition.get("status", "UNKNOWN")).strip() or "UNKNOWN",
                "replacement_metric_key": str(definition.get("replacement_metric_key", "")).strip(),
                "is_default": bool(definition.get("is_default", False)),
                "metadata": metadata,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0011_meta_page_insights_contract_fields"),
    ]

    operations = [
        migrations.RunPython(sync_metric_registry_catalog, migrations.RunPython.noop),
    ]
