# Generated by Django 5.1.14 on 2026-02-21 21:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_rename_accounts_pa_user_id_b7d7a8_idx_accounts_pa_user_id_e5b29b_idx",
        ),
        ("integrations", "0012_sync_meta_metric_catalog"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleAdsParityRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.CharField(max_length=64)),
                ("window_start", models.DateField()),
                ("window_end", models.DateField()),
                (
                    "sdk_spend",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "sdk_clicks",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "sdk_conversions",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "baseline_spend",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "baseline_clicks",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "baseline_conversions",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "spend_delta_pct",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "clicks_delta_pct",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "conversions_delta_pct",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                ("passed", models.BooleanField(default=False)),
                ("reasons", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_ads_parity_runs",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="gads_parity_tenant_created",
                    ),
                    models.Index(
                        fields=["tenant", "passed"], name="gads_parity_tenant_passed"
                    ),
                ],
                "unique_together": {
                    ("tenant", "account_id", "window_start", "window_end")
                },
            },
        ),
        migrations.CreateModel(
            name="GoogleAdsSdkAdGroupAdDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=32)),
                ("campaign_id", models.CharField(max_length=64)),
                ("ad_group_id", models.CharField(max_length=64)),
                ("ad_id", models.CharField(max_length=64)),
                ("campaign_name", models.CharField(blank=True, max_length=255)),
                ("ad_name", models.CharField(blank=True, max_length=255)),
                ("date_day", models.DateField()),
                ("currency_code", models.CharField(blank=True, max_length=16)),
                ("impressions", models.BigIntegerField(default=0)),
                ("clicks", models.BigIntegerField(default=0)),
                (
                    "conversions",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "conversions_value",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("cost_micros", models.BigIntegerField(default=0)),
                ("source_request_id", models.CharField(blank=True, max_length=128)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_ads_sdk_ad_group_ad_daily",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant", "date_day"], name="gads_sdk_ad_day"),
                    models.Index(
                        fields=["tenant", "customer_id"], name="gads_sdk_ad_customer"
                    ),
                ],
                "unique_together": {
                    (
                        "tenant",
                        "customer_id",
                        "campaign_id",
                        "ad_group_id",
                        "ad_id",
                        "date_day",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="GoogleAdsSdkCampaignDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=32)),
                ("campaign_id", models.CharField(max_length=64)),
                ("campaign_name", models.CharField(blank=True, max_length=255)),
                ("date_day", models.DateField()),
                ("currency_code", models.CharField(blank=True, max_length=16)),
                ("impressions", models.BigIntegerField(default=0)),
                ("clicks", models.BigIntegerField(default=0)),
                (
                    "conversions",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "conversions_value",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("cost_micros", models.BigIntegerField(default=0)),
                ("source_request_id", models.CharField(blank=True, max_length=128)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_ads_sdk_campaign_daily",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "date_day"], name="gads_sdk_campaign_day"
                    ),
                    models.Index(
                        fields=["tenant", "customer_id"],
                        name="gads_sdk_campaign_customer",
                    ),
                ],
                "unique_together": {
                    ("tenant", "customer_id", "campaign_id", "date_day")
                },
            },
        ),
        migrations.CreateModel(
            name="GoogleAdsSdkGeographicDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=32)),
                ("campaign_id", models.CharField(max_length=64)),
                ("date_day", models.DateField()),
                ("geo_target_country", models.CharField(blank=True, max_length=128)),
                ("geo_target_region", models.CharField(blank=True, max_length=128)),
                ("geo_target_city", models.CharField(blank=True, max_length=128)),
                ("currency_code", models.CharField(blank=True, max_length=16)),
                ("impressions", models.BigIntegerField(default=0)),
                ("clicks", models.BigIntegerField(default=0)),
                (
                    "conversions",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "conversions_value",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("cost_micros", models.BigIntegerField(default=0)),
                ("source_request_id", models.CharField(blank=True, max_length=128)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_ads_sdk_geographic_daily",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "date_day"], name="gads_sdk_geo_day"
                    ),
                    models.Index(
                        fields=["tenant", "customer_id"], name="gads_sdk_geo_customer"
                    ),
                ],
                "unique_together": {
                    (
                        "tenant",
                        "customer_id",
                        "campaign_id",
                        "date_day",
                        "geo_target_country",
                        "geo_target_region",
                        "geo_target_city",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="GoogleAdsSyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.CharField(max_length=64)),
                (
                    "desired_engine",
                    models.CharField(
                        choices=[("sdk", "SDK"), ("airbyte", "Airbyte")],
                        default="sdk",
                        max_length=16,
                    ),
                ),
                (
                    "effective_engine",
                    models.CharField(
                        choices=[("sdk", "SDK"), ("airbyte", "Airbyte")],
                        default="sdk",
                        max_length=16,
                    ),
                ),
                ("fallback_active", models.BooleanField(default=False)),
                (
                    "parity_state",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("last_parity_passed_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_sdk_failures", models.PositiveIntegerField(default=0)),
                ("consecutive_parity_failures", models.PositiveIntegerField(default=0)),
                ("last_sync_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_error", models.TextField(blank=True)),
                ("rollback_reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_ads_sync_states",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "effective_engine"],
                        name="gads_sync_tenant_engine",
                    ),
                    models.Index(
                        fields=["tenant", "parity_state"],
                        name="gads_sync_tenant_parity",
                    ),
                ],
                "unique_together": {("tenant", "account_id")},
            },
        ),
    ]
