# Generated by Django 5.1.14 on 2026-02-22 02:27

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_rename_accounts_pa_user_id_b7d7a8_idx_accounts_pa_user_id_e5b29b_idx",
        ),
        ("integrations", "0013_googleadsparityrun_googleadssdkadgroupaddaily_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="googleadssdkadgroupaddaily",
            name="ad_status",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="googleadssdkadgroupaddaily",
            name="policy_approval_status",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="googleadssdkadgroupaddaily",
            name="policy_review_status",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="googleadssdkcampaigndaily",
            name="advertising_channel_type",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="googleadssdkcampaigndaily",
            name="campaign_status",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name="GoogleAdsAccountAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=32)),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("analyst", "Analyst"),
                            ("account_manager", "Account Manager"),
                            ("client_read_only", "Client Read Only"),
                        ],
                        default="analyst",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_ads_account_assignments",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_ads_account_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "user"], name="gads_acct_assign_tenant_user"
                    ),
                    models.Index(
                        fields=["tenant", "customer_id"], name="gads_assign_tenant_cust"
                    ),
                ],
                "unique_together": {("tenant", "user", "customer_id")},
            },
        ),
        migrations.CreateModel(
            name="GoogleAdsAccountMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manager_customer_id", models.CharField(blank=True, max_length=32)),
                ("customer_id", models.CharField(max_length=32)),
                ("customer_name", models.CharField(blank=True, max_length=255)),
                ("currency_code", models.CharField(blank=True, max_length=16)),
                ("time_zone", models.CharField(blank=True, max_length=64)),
                ("status", models.CharField(blank=True, max_length=64)),
                ("is_manager", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_ads_account_mappings",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "customer_id"],
                        name="gads_acct_map_tenant_customer",
                    )
                ],
                "unique_together": {("tenant", "customer_id")},
            },
        ),
        migrations.CreateModel(
            name="GoogleAdsSdkAssetGroupDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=32)),
                ("campaign_id", models.CharField(max_length=64)),
                ("asset_group_id", models.CharField(max_length=64)),
                ("asset_group_name", models.CharField(blank=True, max_length=255)),
                ("asset_group_status", models.CharField(blank=True, max_length=32)),
                ("date_day", models.DateField()),
                ("currency_code", models.CharField(blank=True, max_length=16)),
                ("impressions", models.BigIntegerField(default=0)),
                ("clicks", models.BigIntegerField(default=0)),
                (
                    "conversions",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "conversions_value",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("cost_micros", models.BigIntegerField(default=0)),
                ("source_request_id", models.CharField(blank=True, max_length=128)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_ads_sdk_asset_group_daily",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "date_day"], name="gads_sdk_asset_group_day"
                    ),
                    models.Index(
                        fields=["tenant", "customer_id"],
                        name="gads_sdk_asset_group_customer",
                    ),
                ],
                "unique_together": {
                    (
                        "tenant",
                        "customer_id",
                        "campaign_id",
                        "asset_group_id",
                        "date_day",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="GoogleAdsSdkChangeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=32)),
                ("event_fingerprint", models.CharField(max_length=64)),
                ("change_date_time", models.DateTimeField()),
                ("user_email", models.CharField(blank=True, max_length=255)),
                ("client_type", models.CharField(blank=True, max_length=64)),
                ("change_resource_type", models.CharField(blank=True, max_length=64)),
                (
                    "resource_change_operation",
                    models.CharField(blank=True, max_length=64),
                ),
                ("campaign_id", models.CharField(blank=True, max_length=64)),
                ("ad_group_id", models.CharField(blank=True, max_length=64)),
                ("ad_id", models.CharField(blank=True, max_length=64)),
                ("changed_fields", models.JSONField(blank=True, default=list)),
                ("source_request_id", models.CharField(blank=True, max_length=128)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_ads_sdk_change_events",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "change_date_time"],
                        name="gads_sdk_change_event_ts",
                    ),
                    models.Index(
                        fields=["tenant", "customer_id"],
                        name="gads_sdk_change_event_customer",
                    ),
                ],
                "unique_together": {("tenant", "customer_id", "event_fingerprint")},
            },
        ),
        migrations.CreateModel(
            name="GoogleAdsSdkConversionActionDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=32)),
                ("conversion_action_id", models.CharField(max_length=64)),
                (
                    "conversion_action_name",
                    models.CharField(blank=True, max_length=255),
                ),
                ("conversion_action_type", models.CharField(blank=True, max_length=64)),
                ("date_day", models.DateField()),
                (
                    "conversions",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "all_conversions",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "conversions_value",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("source_request_id", models.CharField(blank=True, max_length=128)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_ads_sdk_conversion_action_daily",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "date_day"], name="gads_sdk_conv_action_day"
                    ),
                    models.Index(
                        fields=["tenant", "customer_id"],
                        name="gads_sdk_conv_action_customer",
                    ),
                ],
                "unique_together": {
                    ("tenant", "customer_id", "conversion_action_id", "date_day")
                },
            },
        ),
        migrations.CreateModel(
            name="GoogleAdsSdkKeywordDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=32)),
                ("campaign_id", models.CharField(max_length=64)),
                ("ad_group_id", models.CharField(max_length=64)),
                ("criterion_id", models.CharField(max_length=64)),
                ("keyword_text", models.CharField(blank=True, max_length=255)),
                ("match_type", models.CharField(blank=True, max_length=32)),
                ("criterion_status", models.CharField(blank=True, max_length=32)),
                ("quality_score", models.IntegerField(blank=True, null=True)),
                ("ad_relevance", models.CharField(blank=True, max_length=32)),
                ("expected_ctr", models.CharField(blank=True, max_length=32)),
                (
                    "landing_page_experience",
                    models.CharField(blank=True, max_length=32),
                ),
                ("date_day", models.DateField()),
                ("currency_code", models.CharField(blank=True, max_length=16)),
                ("impressions", models.BigIntegerField(default=0)),
                ("clicks", models.BigIntegerField(default=0)),
                (
                    "conversions",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "conversions_value",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("cost_micros", models.BigIntegerField(default=0)),
                ("source_request_id", models.CharField(blank=True, max_length=128)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_ads_sdk_keyword_daily",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "date_day"], name="gads_sdk_keyword_day"
                    ),
                    models.Index(
                        fields=["tenant", "customer_id"],
                        name="gads_sdk_keyword_customer",
                    ),
                ],
                "unique_together": {
                    (
                        "tenant",
                        "customer_id",
                        "campaign_id",
                        "ad_group_id",
                        "criterion_id",
                        "date_day",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="GoogleAdsSdkRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=32)),
                ("recommendation_type", models.CharField(max_length=64)),
                ("resource_name", models.CharField(max_length=255)),
                ("campaign_id", models.CharField(blank=True, max_length=64)),
                ("ad_group_id", models.CharField(blank=True, max_length=64)),
                ("dismissed", models.BooleanField(default=False)),
                ("impact_metadata", models.JSONField(blank=True, default=dict)),
                ("source_request_id", models.CharField(blank=True, max_length=128)),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_ads_sdk_recommendations",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "dismissed"],
                        name="gads_sdk_reco_tenant_dismissed",
                    ),
                    models.Index(
                        fields=["tenant", "customer_id"],
                        name="gads_sdk_reco_tenant_customer",
                    ),
                ],
                "unique_together": {
                    ("tenant", "customer_id", "recommendation_type", "resource_name")
                },
            },
        ),
        migrations.CreateModel(
            name="GoogleAdsSdkSearchTermDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=32)),
                ("campaign_id", models.CharField(max_length=64)),
                ("ad_group_id", models.CharField(max_length=64)),
                ("criterion_id", models.CharField(blank=True, max_length=64)),
                ("search_term", models.CharField(max_length=255)),
                ("date_day", models.DateField()),
                ("currency_code", models.CharField(blank=True, max_length=16)),
                ("impressions", models.BigIntegerField(default=0)),
                ("clicks", models.BigIntegerField(default=0)),
                (
                    "conversions",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "conversions_value",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("cost_micros", models.BigIntegerField(default=0)),
                ("source_request_id", models.CharField(blank=True, max_length=128)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_ads_sdk_search_term_daily",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "date_day"], name="gads_sdk_search_term_day"
                    ),
                    models.Index(
                        fields=["tenant", "customer_id"],
                        name="gads_sdk_search_term_customer",
                    ),
                ],
                "unique_together": {
                    (
                        "tenant",
                        "customer_id",
                        "campaign_id",
                        "ad_group_id",
                        "search_term",
                        "date_day",
                    )
                },
            },
        ),
    ]
