# Generated by Django 5.1.14 on 2026-03-17 22:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_role_name"),
        ("integrations", "0014_googleadssdkadgroupaddaily_ad_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airbyteconnection",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("META", "Meta"),
                    ("GOOGLE", "Google Ads"),
                    ("GOOGLE_ANALYTICS", "Google Analytics"),
                    ("LINKEDIN", "LinkedIn"),
                    ("TIKTOK", "TikTok"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="apierrorlog",
            name="provider",
            field=models.CharField(
                choices=[
                    ("META", "Meta"),
                    ("GOOGLE", "Google Ads"),
                    ("GOOGLE_ANALYTICS", "Google Analytics"),
                    ("LINKEDIN", "LinkedIn"),
                    ("TIKTOK", "TikTok"),
                ],
                default="META",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="platformcredential",
            name="provider",
            field=models.CharField(
                choices=[
                    ("META", "Meta"),
                    ("GOOGLE", "Google Ads"),
                    ("GOOGLE_ANALYTICS", "Google Analytics"),
                    ("LINKEDIN", "LinkedIn"),
                    ("TIKTOK", "TikTok"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="GoogleAnalyticsConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("property_id", models.CharField(max_length=128)),
                ("property_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("sync_frequency", models.CharField(default="daily", max_length=32)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "credentials",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_analytics_connections",
                        to="integrations.platformcredential",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_analytics_connections",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "is_active"], name="ga4_conn_tenant_active"
                    )
                ],
                "unique_together": {("tenant", "property_id")},
            },
        ),
    ]
