# Generated by Django 5.1.13 on 2026-04-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0016_metaaccountsyncstate_direct_sync_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="metapost",
            name="thumbnail_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="airbyteconnection",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("META", "Meta"),
                    ("GOOGLE", "Google Ads"),
                    ("GOOGLE_ANALYTICS", "Google Analytics"),
                    ("SEARCH_CONSOLE", "Google Search Console"),
                    ("LINKEDIN", "LinkedIn"),
                    ("TIKTOK", "TikTok"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="apierrorlog",
            name="provider",
            field=models.CharField(
                choices=[
                    ("META", "Meta"),
                    ("GOOGLE", "Google Ads"),
                    ("GOOGLE_ANALYTICS", "Google Analytics"),
                    ("SEARCH_CONSOLE", "Google Search Console"),
                    ("LINKEDIN", "LinkedIn"),
                    ("TIKTOK", "TikTok"),
                ],
                default="META",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="platformcredential",
            name="provider",
            field=models.CharField(
                choices=[
                    ("META", "Meta"),
                    ("GOOGLE", "Google Ads"),
                    ("GOOGLE_ANALYTICS", "Google Analytics"),
                    ("SEARCH_CONSOLE", "Google Search Console"),
                    ("LINKEDIN", "LinkedIn"),
                    ("TIKTOK", "TikTok"),
                ],
                max_length=16,
            ),
        ),
    ]
