# Generated by Django 5.1.13 on 2026-04-13 03:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_role_name"),
        ("integrations", "0018_notificationchannel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaRegionDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.CharField(max_length=64)),
                ("date_day", models.DateField()),
                ("region", models.CharField(max_length=128)),
                ("country", models.CharField(blank=True, max_length=128)),
                ("currency", models.CharField(blank=True, max_length=16)),
                ("impressions", models.BigIntegerField(default=0)),
                ("reach", models.BigIntegerField(default=0)),
                ("clicks", models.BigIntegerField(default=0)),
                (
                    "spend",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("conversions", models.IntegerField(default=0)),
                ("actions", models.JSONField(blank=True, default=list)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_region_daily",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant", "date_day"], name="meta_region_day"),
                    models.Index(
                        fields=["tenant", "account_id"], name="meta_region_acct"
                    ),
                ],
                "unique_together": {("tenant", "account_id", "date_day", "region")},
            },
        ),
    ]
