# Generated by Django 5.1.13 on 2026-04-13 05:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_role_name"),
        ("integrations", "0019_meta_region_daily"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="metaregiondaily",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="metaregiondaily",
            name="campaign_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name="metaregiondaily",
            unique_together={
                ("tenant", "account_id", "campaign_id", "date_day", "region")
            },
        ),
        migrations.CreateModel(
            name="MetaAgeGenderDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.CharField(max_length=64)),
                ("date_day", models.DateField()),
                ("age_range", models.CharField(max_length=16)),
                ("gender", models.CharField(max_length=16)),
                ("currency", models.CharField(blank=True, max_length=16)),
                ("impressions", models.BigIntegerField(default=0)),
                ("reach", models.BigIntegerField(default=0)),
                ("clicks", models.BigIntegerField(default=0)),
                (
                    "spend",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("conversions", models.IntegerField(default=0)),
                ("actions", models.JSONField(blank=True, default=list)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_age_gender_daily",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "date_day"], name="meta_agegender_day"
                    ),
                    models.Index(
                        fields=["tenant", "account_id"], name="meta_agegender_acct"
                    ),
                ],
                "unique_together": {
                    ("tenant", "account_id", "date_day", "age_range", "gender")
                },
            },
        ),
    ]
