# Generated by Django 5.1.14 on 2026-04-13 06:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_role_name"),
        ("integrations", "0020_add_campaign_id_and_age_gender_daily"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaPlatformDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.CharField(max_length=64)),
                ("date_day", models.DateField()),
                ("publisher_platform", models.CharField(max_length=32)),
                ("device_platform", models.CharField(max_length=32)),
                ("currency", models.CharField(blank=True, max_length=16)),
                ("impressions", models.BigIntegerField(default=0)),
                ("reach", models.BigIntegerField(default=0)),
                ("clicks", models.BigIntegerField(default=0)),
                (
                    "spend",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("conversions", models.IntegerField(default=0)),
                ("actions", models.JSONField(blank=True, default=list)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_platform_daily",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "date_day"], name="meta_platform_day"
                    ),
                    models.Index(
                        fields=["tenant", "account_id"], name="meta_platform_acct"
                    ),
                ],
                "unique_together": {
                    (
                        "tenant",
                        "account_id",
                        "date_day",
                        "publisher_platform",
                        "device_platform",
                    )
                },
            },
        ),
    ]
