# Generated by Django 5.2.13 on 2026-04-14 04:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_role_name"),
        ("integrations", "0021_add_platform_daily"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("industry", models.CharField(blank=True, max_length=128)),
                ("parish", models.CharField(blank=True, max_length=64)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ClientPlatformAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("google_ads", "Google Ads"),
                            ("meta_ads", "Meta Ads"),
                            ("meta_page", "Meta Page"),
                            ("ga4", "Google Analytics 4"),
                            ("search_console", "Google Search Console"),
                            ("linkedin", "LinkedIn"),
                            ("tiktok", "TikTok"),
                        ],
                        max_length=32,
                    ),
                ),
                ("external_id", models.CharField(max_length=128)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_accounts",
                        to="integrations.client",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_platform_accounts",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("platform", "external_id"),
            },
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["tenant", "is_active"], name="client_tenant_active"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="client",
            unique_together={("tenant", "slug")},
        ),
        migrations.AddIndex(
            model_name="clientplatformaccount",
            index=models.Index(
                fields=["tenant", "client", "platform"],
                name="client_platacc_tenant_cli_plat",
            ),
        ),
        migrations.AddIndex(
            model_name="clientplatformaccount",
            index=models.Index(
                fields=["tenant", "platform", "external_id"],
                name="client_platacc_tenant_ext",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clientplatformaccount",
            unique_together={("tenant", "platform", "external_id")},
        ),
    ]
