# Generated by Django 5.1.13 on 2026-07-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0026_notificationchannel_secret_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="metapage",
            name="instagram_business_account_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="metapage",
            name="instagram_username",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
