version: 2

sources:
  - name: meta_raw
    schema: raw_meta
    tables:
      - name: ad_insights
      - name: campaigns
      - name: ads
      - name: adsets

models:
  - name: stg_meta_insights
    description: "Normalized daily Meta insights metrics"
  - name: stg_meta_campaigns
    description: "Meta campaign metadata"
  - name: stg_meta_ads_metadata
    description: "Meta ad metadata"
  - name: stg_meta_adsets
    description: "Meta ad set metadata"
