# Generated by Django 5.0.6 on 2025-10-13 20:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_invitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantMetricsSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source", models.CharField(default="combined", max_length=64)),
                ("payload", models.JSONField(default=dict)),
                (
                    "generated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics_snapshots",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("-generated_at", "-created_at"),
                "unique_together": {("tenant", "source")},
            },
        ),
    ]
