# Generated by Django 5.1.13 on 2025-10-22 15:18

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_rename_accounts_pa_user_id_b7d7a8_idx_accounts_pa_user_id_e5b29b_idx",
        ),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=255)),
                ("status", models.CharField(blank=True, max_length=32)),
                ("bid_strategy", models.CharField(blank=True, max_length=64)),
                (
                    "daily_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=Decimal("0"),
                        max_digits=20,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("targeting", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_adsets",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "external_id"),
            },
        ),
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=255)),
                ("status", models.CharField(blank=True, max_length=32)),
                ("creative", models.JSONField(blank=True, default=dict)),
                ("preview_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_ads",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "adset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads",
                        to="analytics.adset",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "external_id"),
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=255)),
                ("platform", models.CharField(max_length=32)),
                ("account_external_id", models.CharField(blank=True, max_length=128)),
                ("status", models.CharField(blank=True, max_length=32)),
                ("objective", models.CharField(blank=True, max_length=64)),
                ("currency", models.CharField(blank=True, max_length=16)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_time", models.DateTimeField(blank=True, null=True)),
                ("updated_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_campaigns",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "external_id"),
            },
        ),
        migrations.AddField(
            model_name="adset",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adsets",
                to="analytics.campaign",
            ),
        ),
        migrations.CreateModel(
            name="RawPerformanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.CharField(max_length=128)),
                ("date", models.DateField()),
                ("source", models.CharField(max_length=32)),
                ("impressions", models.PositiveBigIntegerField(default=0)),
                ("clicks", models.PositiveBigIntegerField(default=0)),
                (
                    "spend",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=16)),
                ("conversions", models.IntegerField(default=0)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_records",
                        to="analytics.ad",
                    ),
                ),
                (
                    "adset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_records",
                        to="analytics.adset",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_records",
                        to="analytics.campaign",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_performance_records",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("-date", "-ingested_at"),
            },
        ),
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(
                fields=["tenant", "external_id"], name="analytics_ad_ext"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ad",
            unique_together={("tenant", "external_id")},
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["tenant", "external_id"], name="analytics_campaign_ext"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="campaign",
            unique_together={("tenant", "external_id")},
        ),
        migrations.AddIndex(
            model_name="adset",
            index=models.Index(
                fields=["tenant", "external_id"], name="analytics_adset_ext"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="adset",
            unique_together={("tenant", "external_id")},
        ),
        migrations.AddIndex(
            model_name="rawperformancerecord",
            index=models.Index(
                fields=["tenant", "external_id"], name="analytics_perf_ext"
            ),
        ),
        migrations.AddIndex(
            model_name="rawperformancerecord",
            index=models.Index(fields=["tenant", "date"], name="analytics_perf_date"),
        ),
    ]
