# Generated by Django 5.1.14 on 2026-02-19 15:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_rename_accounts_pa_user_id_b7d7a8_idx_accounts_pa_user_id_e5b29b_idx",
        ),
        ("analytics", "0003_reportdefinition_reportexportjob_aisummary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.CharField(max_length=128)),
                ("account_id", models.CharField(blank=True, max_length=128)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("currency", models.CharField(blank=True, max_length=16)),
                ("status", models.CharField(blank=True, max_length=32)),
                ("business_name", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_time", models.DateTimeField(blank=True, null=True)),
                ("updated_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_ad_accounts",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "external_id"),
                "indexes": [
                    models.Index(
                        fields=["tenant", "external_id"],
                        name="analytics_adacct_ext",
                    ),
                    models.Index(
                        fields=["tenant", "account_id"],
                        name="analytics_adacct_account",
                    ),
                ],
                "unique_together": {("tenant", "external_id")},
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="ad_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="analytics.adaccount",
            ),
        ),
        migrations.AddField(
            model_name="rawperformancerecord",
            name="actions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="rawperformancerecord",
            name="ad_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performance_records",
                to="analytics.adaccount",
            ),
        ),
        migrations.AddField(
            model_name="rawperformancerecord",
            name="cpc",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="rawperformancerecord",
            name="cpm",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="rawperformancerecord",
            name="level",
            field=models.CharField(default="ad", max_length=16),
        ),
        migrations.AddField(
            model_name="rawperformancerecord",
            name="reach",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["tenant", "ad_account"],
                name="analytics_campaign_account",
            ),
        ),
        migrations.AddIndex(
            model_name="rawperformancerecord",
            index=models.Index(
                fields=["tenant", "ad_account", "date"],
                name="analytics_perf_acct_date",
            ),
        ),
        migrations.AddIndex(
            model_name="rawperformancerecord",
            index=models.Index(
                fields=["tenant", "level", "date"],
                name="analytics_perf_level_date",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rawperformancerecord",
            unique_together={("tenant", "source", "external_id", "date", "level")},
        ),
    ]
