# Generated by Django 5.1.13 on 2026-04-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0006_dashboarddefinition"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportdefinition",
            name="delivery_emails",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="reportdefinition",
            name="last_scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reportdefinition",
            name="schedule_cron",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="reportdefinition",
            name="schedule_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="dashboarddefinition",
            name="template_key",
            field=models.CharField(
                choices=[
                    ("meta_executive_overview", "Meta executive overview"),
                    ("meta_campaign_performance", "Meta campaign performance"),
                    ("meta_creative_insights", "Meta creative insights"),
                    ("meta_budget_pacing", "Meta budget pacing"),
                    ("meta_parish_map", "Meta parish map"),
                    ("meta_page_insights", "Meta page insights"),
                ],
                default="meta_campaign_performance",
                max_length=64,
            ),
        ),
    ]
