version: 2

models:
  - name: agg_campaign_daily
    description: 'Incremental aggregate of campaign-level performance metrics with geo enrichment from the campaign dimension.'
    tests:
      - unique_combination_of_columns:
          arguments:
            combination:
              - tenant_id
              - date_day
              - source_platform
              - ad_account_id
              - campaign_id
    columns:
      - name: tenant_id
        description: 'Tenant scope for the aggregated record.'
        tests:
          - not_null
      - name: date_day
        description: 'Calendar date the metrics are aggregated for.'
        tests:
          - not_null
      - name: parish_code
        description: 'Geographic parish code receiving the spend.'
      - name: parish_name
        description: 'Friendly parish name from the geo dimension.'
      - name: region_name
        description: 'Region grouping for the parish.'
      - name: spend
        description: 'Total spend attributed to the parish on the given day.'
      - name: impressions
        description: 'Total impressions served within the parish on the given day.'
      - name: clicks
        description: 'Total clicks generated within the parish on the given day.'
      - name: conversions
        description: 'Total conversions attributed to the parish on the given day.'
      - name: ctr
        description: 'Click-through rate derived from parish clicks divided by impressions.'
      - name: conversion_rate
        description: 'Conversion rate derived from parish conversions divided by clicks.'
      - name: cost_per_click
        description: 'Average cost per click within the parish.'
      - name: cost_per_conversion
        description: 'Average cost per conversion within the parish.'
      - name: cpm
        description: 'Cost per 1,000 impressions within the parish.'
      - name: roas
        description: 'Return on ad spend for the parish derived from conversions divided by spend.'
        tests:
          - expression_is_true:
              arguments:
                expression: 'coalesce(roas, 0) >= 0'
  - name: agg_parish_daily
    description: 'Incremental parish-level aggregate used by the choropleth map and dashboard summaries.'
    tests:
      - unique_combination_of_columns:
          arguments:
            combination:
              - tenant_id
              - date_day
              - parish_code
    columns:
      - name: tenant_id
        description: 'Tenant scope for the aggregated record.'
        tests:
          - not_null
      - name: date_day
        description: 'Calendar date the metrics are aggregated for.'
        tests:
          - not_null
      - name: parish_code
        description: 'Geographic parish code receiving the spend.'
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_geo')
                field: parish_code
      - name: parish_name
        description: 'Friendly parish name from the geo dimension.'
      - name: region_name
        description: 'Region grouping for the parish.'
      - name: spend
        description: 'Total spend attributed to the parish on the given day.'
      - name: impressions
        description: 'Total impressions served within the parish on the given day.'
      - name: clicks
        description: 'Total clicks generated within the parish on the given day.'
      - name: conversions
        description: 'Total conversions attributed to the parish on the given day.'
      - name: campaign_count
        description: 'Number of distinct campaigns contributing to the parish totals on the given day.'
        tests:
          - expression_is_true:
              arguments:
                expression: 'coalesce(campaign_count, 0) >= 0'
      - name: ctr
        description: 'Click-through rate derived from parish clicks divided by impressions.'
      - name: conversion_rate
        description: 'Conversion rate derived from parish conversions divided by clicks.'
      - name: cost_per_click
        description: 'Average cost per click within the parish.'
      - name: cost_per_conversion
        description: 'Average cost per conversion within the parish.'
      - name: cpm
        description: 'Cost per 1,000 impressions within the parish.'
      - name: roas
        description: 'Return on ad spend for the parish derived from conversions divided by spend.'
  - name: vw_campaign_daily
    description: 'Aggregated daily campaign metrics joined to current campaign attributes.'
    tests:
      - unique_combination_of_columns:
          arguments:
            combination:
              - tenant_id
              - date_day
              - source_platform
              - ad_account_id
              - campaign_id
    columns:
      - name: tenant_id
        description: 'Tenant identifier for row-level isolation.'
        tests:
          - not_null
      - name: date_day
        tests:
          - not_null
      - name: source_platform
        description: 'Advertising platform the campaign belongs to.'
      - name: ad_account_id
        description: 'Unique identifier for the ad account owning the campaign.'
        tests:
          - not_null
      - name: campaign_id
        description: 'Unique identifier for the campaign receiving spend.'
        tests:
          - not_null
      - name: campaign_name
        description: 'Human friendly campaign name, falling back to the campaign ID when metadata is missing.'
        tests:
          - not_null
      - name: reported_conversions
        description: 'Platform-reported conversions prior to attribution window normalization.'
      - name: conversions
        tests:
          - expression_is_true:
              arguments:
                expression: 'coalesce(conversions, 0) >= 0'
      - name: cost_per_click
        description: 'Average cost per click for the campaign on the given day.'
        tests:
          - expression_is_true:
              arguments:
                expression: 'coalesce(cost_per_click, 0) >= 0'
      - name: ctr
      - name: roas
      - name: cpm
        tests:
          - expression_is_true:
              arguments:
                expression: 'coalesce(cpm, 0) >= 0'
      - name: conversion_rate
        tests:
          - expression_is_true:
              arguments:
                expression: 'coalesce(conversion_rate, 0) >= 0'
      - name: cost_per_conversion
        tests:
          - expression_is_true:
              arguments:
                expression: 'coalesce(cost_per_conversion, 0) >= 0'
  - name: vw_creative_daily
    description: 'Aggregated daily creative metrics with cost efficiency fields for dashboards.'
    tests:
      - unique_combination_of_columns:
          arguments:
            combination:
              - tenant_id
              - date_day
              - source_platform
              - ad_account_id
              - campaign_id
              - adset_id
              - ad_id
    columns:
      - name: tenant_id
        tests:
          - not_null
      - name: date_day
        tests:
          - not_null
      - name: source_platform
        description: 'Conversions normalized to the configured attribution window.'
        tests:
          - not_null
      - name: parish_code
        tests:
          - relationships:
              arguments:
                to: ref('dim_geo')
                field: parish_code
      - name: spend
        tests:
          - expression_is_true:
              arguments:
                expression: 'coalesce(spend, 0) >= 0'
      - name: impressions
        tests:
          - expression_is_true:
              arguments:
                expression: 'coalesce(impressions, 0) >= 0'
      - name: clicks
        tests:
          - expression_is_true:
              arguments:
                expression: 'coalesce(clicks, 0) >= 0'
      - name: conversions
        tests:
          - expression_is_true:
              arguments:
                expression: 'coalesce(conversions, 0) >= 0'
      - name: cost_per_click
        description: 'Average cost per click for the account on the given day.'
        tests:
          - expression_is_true:
              arguments:
                expression: 'coalesce(cost_per_click, 0) >= 0'
      - name: conversion_rate
        tests:
          - expression_is_true:
              arguments:
                expression: 'coalesce(conversion_rate, 0) >= 0'
      - name: cost_per_conversion
        tests:
          - expression_is_true:
              arguments:
                expression: 'coalesce(cost_per_conversion, 0) >= 0'
      - name: roas
      - name: cpm
        tests:
          - expression_is_true:
              arguments:
                expression: 'coalesce(cpm, 0) >= 0'
  - name: vw_pacing
    description: 'Account level pacing view with cumulative and trailing spend indicators.'
    tests:
      - unique_combination_of_columns:
          arguments:
            combination:
              - tenant_id
              - date_day
              - source_platform
              - ad_account_id
    columns:
      - name: tenant_id
        tests:
          - not_null
      - name: date_day
        tests:
          - not_null
      - name: conversions
        tests:
          - expression_is_true:
              arguments:
                expression: 'coalesce(conversions, 0) >= 0'
      - name: cost_per_click
        tests:
          - expression_is_true:
              arguments:
                expression: 'coalesce(cost_per_click, 0) >= 0'
      - name: cumulative_spend
        tests:
          - expression_is_true:
              arguments:
                expression: 'coalesce(cumulative_spend, 0) >= 0'
      - name: trailing_7d_avg_spend
        tests:
          - expression_is_true:
              arguments:
                expression: 'coalesce(trailing_7d_avg_spend, 0) >= 0'
      - name: ctr
        tests:
          - expression_is_true:
              arguments:
                expression: 'coalesce(ctr, 0) >= 0'
      - name: roas
      - name: cpm
        tests:
          - expression_is_true:
              arguments:
                expression: 'coalesce(cpm, 0) >= 0'
      - name: conversion_rate
        tests:
          - expression_is_true:
              arguments:
                expression: 'coalesce(conversion_rate, 0) >= 0'
      - name: cost_per_conversion
        tests:
          - expression_is_true:
              arguments:
                expression: 'coalesce(cost_per_conversion, 0) >= 0'
      - name: pacing_vs_7d_avg
        description: 'Ratio of current spend to the trailing seven day average spend.'
        tests:
          - expression_is_true:
              arguments:
                expression: 'coalesce(pacing_vs_7d_avg, 0) >= 0'
          - not_null
      - name: reported_conversions
        description: 'Platform reported conversions prior to normalization.'

  - name: vw_dashboard_aggregate_snapshot
    description: 'Aggregated JSON payload per tenant used by the backend dashboard snapshot pipeline.'
    columns:
      - name: tenant_id
        description: 'Tenant identifier for row-level isolation.'
        tests:
          - not_null
          - unique
      - name: generated_at
        description: 'Timestamp of the latest underlying warehouse record included in the snapshot.'
        tests:
          - not_null
      - name: campaign_metrics
        description: 'Campaign summary/trend/table payload matching the frontend campaign schema.'
        tests:
          - not_null
          - expression_is_true:
              arguments:
                expression: "{{ json_typeof('campaign_metrics') }} = 'object'"
      - name: creative_metrics
        description: 'Creative performance rows matching the frontend creative schema.'
        tests:
          - not_null
          - expression_is_true:
              arguments:
                expression: "{{ json_typeof('creative_metrics') }} = 'array'"
      - name: budget_metrics
        description: 'Budget pacing rows sourced from Meta ad set daily budgets with windowed spend.'
        tests:
          - not_null
          - expression_is_true:
              arguments:
                expression: "{{ json_typeof('budget_metrics') }} = 'array'"
      - name: parish_metrics
        description: 'Parish aggregate rows matching the frontend map schema.'
        tests:
          - not_null
          - expression_is_true:
              arguments:
                expression: "{{ json_typeof('parish_metrics') }} = 'array'"
  - name: agg_ga4_daily
    description: 'Phase 2 GA4 daily aggregate for web analytics trends and reporting.'
    config:
      enabled: "{{ var('enable_ga4', False) }}"
    tests:
      - unique_combination_of_columns:
          arguments:
            combination:
              - tenant_id
              - date_day
              - property_id
              - channel_group
              - country
              - city
              - campaign_name
    columns:
      - name: tenant_id
        tests:
          - not_null:
              config:
                enabled: "{{ var('enable_ga4', False) }}"
      - name: date_day
        tests:
          - not_null:
              config:
                enabled: "{{ var('enable_ga4', False) }}"
      - name: sessions
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(sessions, 0) >= 0"
              config:
                enabled: "{{ var('enable_ga4', False) }}"
      - name: purchase_revenue
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(purchase_revenue, 0) >= 0"
              config:
                enabled: "{{ var('enable_ga4', False) }}"
  - name: agg_search_console_daily
    description: 'Phase 2 Search Console aggregate for SEO performance analysis.'
    config:
      enabled: "{{ var('enable_search_console', False) }}"
    tests:
      - unique_combination_of_columns:
          arguments:
            combination:
              - tenant_id
              - date_day
              - site_url
              - country
              - device
              - query
              - page
    columns:
      - name: tenant_id
        tests:
          - not_null:
              config:
                enabled: "{{ var('enable_search_console', False) }}"
      - name: date_day
        tests:
          - not_null:
              config:
                enabled: "{{ var('enable_search_console', False) }}"
      - name: clicks
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(clicks, 0) >= 0"
              config:
                enabled: "{{ var('enable_search_console', False) }}"
      - name: impressions
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(impressions, 0) >= 0"
              config:
                enabled: "{{ var('enable_search_console', False) }}"
