version: 2

models:
  - name: dim_campaign
    description: "SCD2 dimension capturing campaign level attributes and geo enrichment."
    columns:
      - name: source_platform
        tests:
          - not_null
      - name: ad_account_id
        tests:
          - not_null
      - name: campaign_id
        tests:
          - not_null
      - name: parish_code
      - name: valid_from
        tests:
          - not_null
      - name: valid_to
      - name: is_current
  - name: dim_adset
    description: "SCD2 dimension for ad sets/ad groups mapped back to campaigns and locations."
    columns:
      - name: source_platform
      - name: ad_account_id
      - name: adset_id
        tests:
          - not_null
      - name: campaign_id
      - name: parish_code
      - name: valid_from
      - name: valid_to
  - name: dim_ad
    description: "SCD2 dimension for creatives with ad set, campaign, and geo attributes."
    columns:
      - name: source_platform
      - name: ad_account_id
      - name: ad_id
        tests:
          - not_null
      - name: adset_id
      - name: campaign_id
      - name: parish_code
      - name: valid_from
  - name: dim_geo
    description: "Static lookup table mapping Jamaican parishes to geographic metadata."
    columns:
      - name: parish_code
        tests:
          - not_null
          - unique
      - name: parish_name
      - name: region_name
  - name: fct_ad_performance
    description: "Daily fact table for spend and performance metrics across platforms."
    columns:
      - name: date_day
        tests:
          - not_null
      - name: source_platform
        tests:
          - not_null
      - name: ad_account_id
        tests:
          - not_null
      - name: campaign_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_campaign')
                field: campaign_id
      - name: campaign_name
        description: "Human-readable campaign label sourced from staging when available."
        tests:
          - not_null
      - name: adset_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_adset')
                field: adset_id
      - name: ad_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_ad')
                field: ad_id
      - name: parish_code
        tests:
          - relationships:
              arguments:
                to: ref('dim_geo')
                field: parish_code
      - name: spend
        tests:
          - not_null
          - expression_is_true:
              arguments:
                expression: "coalesce(spend, 0) >= 0"
      - name: impressions
        tests:
          - not_null
          - expression_is_true:
              arguments:
                expression: "coalesce(impressions, 0) >= 0"
      - name: clicks
        tests:
          - not_null
          - expression_is_true:
              arguments:
                expression: "coalesce(clicks, 0) >= 0"
      - name: conversions
        tests:
          - not_null
          - expression_is_true:
              arguments:
                expression: "coalesce(conversions, 0) >= 0"
      - name: ctr
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(ctr, 0) >= 0"
      - name: conversion_rate
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(conversion_rate, 0) >= 0"
      - name: roas
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(roas, 0) >= 0"
  - name: agg_campaign_daily
    description: "Incremental aggregate of campaign-level performance metrics with geo enrichment from the campaign dimension."
    columns:
      - name: date_day
        description: "Calendar date the metrics are aggregated for."
        tests:
          - not_null
      - name: source_platform
        description: "Advertising platform the campaign belongs to."
      - name: ad_account_id
        description: "Unique identifier for the ad account owning the campaign."
      - name: campaign_id
        description: "Unique identifier for the campaign receiving spend."
      - name: campaign_name
        description: "Human-readable campaign label favoring staging data with dimensional fallback."
      - name: spend
        description: "Total spend attributed to the campaign on the given day."
      - name: impressions
        description: "Total impressions delivered by the campaign on the given day."
      - name: clicks
        description: "Total clicks generated by the campaign on the given day."
      - name: conversions
        description: "Total conversions attributed to the campaign on the given day."
      - name: ctr
        description: "Click-through rate derived from clicks divided by impressions."
      - name: conversion_rate
        description: "Conversion rate derived from conversions divided by clicks."
      - name: cost_per_click
        description: "Average cost per click for the campaign on the given day."
      - name: cost_per_conversion
        description: "Average cost per conversion for the campaign on the given day."
      - name: cpm
        description: "Cost per 1,000 impressions for the campaign on the given day."
      - name: parish_code
        description: "Geographic parish code associated with the campaign during the day."
      - name: parish_name
        description: "Friendly name of the parish associated with the campaign."
      - name: region_name
        description: "Region grouping tied to the parish."
      - name: first_seen_date
        description: "First date the campaign was observed in the warehouse."
  - name: agg_parish_daily
    description: "Daily parish-level aggregation of spend and performance metrics with geo metadata."
    columns:
      - name: date_day
        description: "Calendar date the metrics are aggregated for."
        tests:
          - not_null
      - name: parish_code
        description: "Geographic parish code receiving the spend."
      - name: parish_name
        description: "Friendly parish name from the geo dimension."
      - name: region_name
        description: "Region grouping for the parish."
      - name: spend
        description: "Total spend attributed to the parish on the given day."
      - name: impressions
        description: "Total impressions served within the parish on the given day."
      - name: clicks
        description: "Total clicks generated within the parish on the given day."
      - name: conversions
        description: "Total conversions attributed to the parish on the given day."
      - name: ctr
        description: "Click-through rate derived from parish clicks divided by impressions."
      - name: conversion_rate
        description: "Conversion rate derived from parish conversions divided by clicks."
      - name: cost_per_click
        description: "Average cost per click within the parish."
      - name: cost_per_conversion
        description: "Average cost per conversion within the parish."
      - name: cpm
        description: "Cost per 1,000 impressions within the parish."
  - name: vw_campaign_daily
    description: "Aggregated daily campaign metrics joined to current campaign attributes."
    columns:
      - name: date_day
        tests:
          - not_null
      - name: source_platform
        tests:
          - not_null
      - name: ad_account_id
        tests:
          - not_null
      - name: campaign_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_campaign')
                field: campaign_id
      - name: campaign_name
        description: "Human-readable campaign label favoring staging data with dimensional fallback."
      - name: parish_code
        tests:
          - relationships:
              arguments:
                to: ref('dim_geo')
                field: parish_code
      - name: spend
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(spend, 0) >= 0"
      - name: impressions
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(impressions, 0) >= 0"
      - name: clicks
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(clicks, 0) >= 0"
      - name: conversions
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(conversions, 0) >= 0"
      - name: ctr
      - name: roas
      - name: cpm
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(cpm, 0) >= 0"
      - name: conversion_rate
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(conversion_rate, 0) >= 0"
      - name: cost_per_conversion
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(cost_per_conversion, 0) >= 0"
  - name: vw_creative_daily
    description: "Aggregated daily creative metrics with cost efficiency fields for dashboards."
    columns:
      - name: date_day
        tests:
          - not_null
      - name: source_platform
        tests:
          - not_null
      - name: ad_account_id
        tests:
          - not_null
      - name: ad_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_ad')
                field: ad_id
      - name: adset_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_adset')
                field: adset_id
      - name: campaign_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_campaign')
                field: campaign_id
      - name: parish_code
        tests:
          - relationships:
              arguments:
                to: ref('dim_geo')
                field: parish_code
      - name: spend
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(spend, 0) >= 0"
      - name: impressions
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(impressions, 0) >= 0"
      - name: clicks
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(clicks, 0) >= 0"
      - name: conversions
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(conversions, 0) >= 0"
      - name: cost_per_click
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(cost_per_click, 0) >= 0"
      - name: conversion_rate
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(conversion_rate, 0) >= 0"
      - name: cost_per_conversion
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(cost_per_conversion, 0) >= 0"
      - name: roas
      - name: cpm
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(cpm, 0) >= 0"
  - name: vw_pacing
    description: "Account level pacing view with cumulative and trailing spend indicators."
    columns:
      - name: date_day
        tests:
          - not_null
      - name: source_platform
        tests:
          - not_null
      - name: ad_account_id
        tests:
          - not_null
      - name: spend
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(spend, 0) >= 0"
      - name: impressions
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(impressions, 0) >= 0"
      - name: clicks
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(clicks, 0) >= 0"
      - name: conversions
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(conversions, 0) >= 0"
      - name: cumulative_spend
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(cumulative_spend, 0) >= 0"
      - name: trailing_7d_avg_spend
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(trailing_7d_avg_spend, 0) >= 0"
      - name: ctr
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(ctr, 0) >= 0"
      - name: roas
      - name: cpm
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(cpm, 0) >= 0"
      - name: conversion_rate
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(conversion_rate, 0) >= 0"
      - name: cost_per_conversion
        tests:
          - expression_is_true:
              arguments:
                expression: "coalesce(cost_per_conversion, 0) >= 0"
