version: 2

models:
  - name: agg_campaign_daily
    description: 'Incremental aggregate of campaign-level performance metrics with geo enrichment from the campaign dimension.'
    columns:
      - name: tenant_id
        description: 'Tenant scope for the aggregated record.'
        tests:
          - not_null
      - name: date_day
        description: 'Calendar date the metrics are aggregated for.'
        tests:
          - not_null
      - name: source_platform
        description: 'Advertising platform the campaign belongs to.'
      - name: ad_account_id
        description: 'Unique identifier for the ad account owning the campaign.'
        tests:
          - not_null
      - name: campaign_id
        description: 'Unique identifier for the campaign receiving spend.'
        tests:
          - not_null
      - name: campaign_name
        description: 'Human friendly campaign name, falling back to the campaign ID when metadata is missing.'
        tests:
          - not_null
      - name: reported_conversions
        description: 'Platform-reported conversions prior to attribution window normalization.'
      - name: conversions
        description: 'Conversions normalized to the configured attribution window.'
        tests:
          - not_null
      - name: parish_code
        tests:
          - relationships:
              to: ref('dim_geo')
              field: parish_code
  - name: agg_parish_daily
    description: 'Incremental aggregate of parish-level performance metrics enriched with geo dimension data.'
    columns:
      - name: tenant_id
        tests:
          - not_null
      - name: date_day
        tests:
          - not_null
      - name: parish_code
        tests:
          - not_null
          - relationships:
              to: ref('dim_geo')
              field: parish_code
      - name: conversions
        tests:
          - not_null
      - name: reported_conversions
        description: 'Platform reported conversions prior to normalization.'
