{% set default_google_ads_metrics_query -%}
SELECT
  segments.date                  AS date_day,
  customer.id                    AS customer_id,
  campaign.id                    AS campaign_id,
  campaign.name                  AS campaign_name,
  ad_group.id                    AS ad_group_id,
  ad_group_ad.ad.id              AS criterion_id,
  ad_group_ad.ad.name            AS ad_name,
  segments.device                AS device,
  segments.geo_target_region     AS geo_target_region,
  metrics.cost_micros            AS cost_micros,
  customer.currency_code         AS currency_code,
  metrics.impressions            AS impressions,
  metrics.clicks                 AS clicks,
  metrics.conversions            AS conversions,
  metrics.conversions_value      AS conversions_value
FROM ad_group_ad
WHERE segments.date BETWEEN '{{ runtime_from_date }}' AND '{{ runtime_to_date }}'
{%- endset %}
{
  "sourceDefinitionId": "0b29e8f7-f64c-4a24-9e97-07c4603f8c04",
  "workspaceId": "{{ env['AIRBYTE_WORKSPACE_ID'] }}",
  "name": "Google Ads Incremental",
  "connectionConfiguration": {
    "developer_token": "{{ env['AIRBYTE_GOOGLE_ADS_DEVELOPER_TOKEN'] }}",
    "client_id": "{{ env['AIRBYTE_GOOGLE_ADS_CLIENT_ID'] }}",
    "client_secret": "{{ env['AIRBYTE_GOOGLE_ADS_CLIENT_SECRET'] }}",
    "refresh_token": "{{ env['AIRBYTE_GOOGLE_ADS_REFRESH_TOKEN'] }}",
    "customer_id": "{{ env['AIRBYTE_GOOGLE_ADS_CUSTOMER_ID'] }}",
    "login_customer_id": "{{ env['AIRBYTE_GOOGLE_ADS_LOGIN_CUSTOMER_ID'] }}",
    "start_date": "{{ env.get('AIRBYTE_GOOGLE_ADS_START_DATE', '2023-01-01') }}",
    "conversion_window": {{ env.get('AIRBYTE_GOOGLE_ADS_CONVERSION_WINDOW_DAYS', 30) }},
    "lookback_window": {{ env.get('AIRBYTE_GOOGLE_ADS_LOOKBACK_WINDOW_DAYS', 3) }},
    "include_zero_impressions": true,
    "custom_queries": [
      {
        "query": "{{ env.get('AIRBYTE_GOOGLE_ADS_CUSTOM_QUERY', default_google_ads_metrics_query) | trim | replace('"', '\\"') }}",
        "cursor_field": "date_day",
        "primary_key": [
          "campaign_id",
          "ad_group_id",
          "criterion_id",
          "date_day"
        ]
      }
    ]
  },
  "streams": [
    {
      "name": "ad_group_ad_performance",
      "syncMode": "incremental",
      "cursorField": [
        "date_day"
      ],
      "primaryKey": [
        [
          "campaign_id"
        ],
        [
          "ad_group_id"
        ],
        [
          "criterion_id"
        ],
        [
          "date_day"
        ]
      ],
      "destinationSyncMode": "append_dedup"
    }
  ]
}
