{% set default_google_ads_metrics_query -%}
SELECT
  segments.date,
  customer.id,
  campaign.id,
  ad_group.id,
  metrics.cost_micros,
  metrics.impressions,
  metrics.clicks,
  metrics.conversions,
  segments.geo_target_region
FROM ad_group
WHERE segments.date BETWEEN '{{ runtime_from_date }}' AND '{{ runtime_to_date }}'
{%- endset %}

# Google Ads source configuration for Airbyte
sourceDefinitionId: 0b29e8f7-f64c-4a24-9e97-07c4603f8c04  # Official Google Ads source
workspaceId: {{ env['AIRBYTE_WORKSPACE_ID'] }}
name: "Google Ads Incremental"
connectionConfiguration:
  developer_token: {{ env['AIRBYTE_GOOGLE_ADS_DEVELOPER_TOKEN'] }}
  client_id: {{ env['AIRBYTE_GOOGLE_ADS_CLIENT_ID'] }}
  client_secret: {{ env['AIRBYTE_GOOGLE_ADS_CLIENT_SECRET'] }}
  refresh_token: {{ env['AIRBYTE_GOOGLE_ADS_REFRESH_TOKEN'] }}
  customer_id: {{ env['AIRBYTE_GOOGLE_ADS_CUSTOMER_ID'] }}
  login_customer_id: {{ env['AIRBYTE_GOOGLE_ADS_LOGIN_CUSTOMER_ID'] }}
  start_date: "2023-01-01"
  end_date: null
  conversion_window: 30
  lookback_window: 30
  include_zero_impressions: true
  custom_queries:
    - query: |
        {{ env.get('AIRBYTE_GOOGLE_ADS_CUSTOM_QUERY', default_google_ads_metrics_query) | trim | indent(8, true) }}
      cursor_field: segments.date
      primary_key:
        - campaign.id
        - ad_group.id
        - segments.date
streams:
  - name: ad_group_performance
    syncMode: incremental
    cursorField:
      - segments.date
    primaryKey:
      - - campaign.id
        - ad_group.id
        - segments.date
    destinationSyncMode: append_dedup
