# Stub connector configuration for LinkedIn transparency data
# This uses the Generic HTTP source with CSV/JSON parser as a placeholder until a formal connector is implemented.
sourceDefinitionId: 0eb38cfb-7dce-4b03-8a5d-74ac8605e885  # Airbyte HTTP API source
workspaceId: <replace-with-workspace-uuid>
name: "LinkedIn Transparency (Stub)"
connectionConfiguration:
  provider:
    auth_type: oauth2
    client_id: {{ env['AIRBYTE_LINKEDIN_CLIENT_ID'] }}
    client_secret: {{ env['AIRBYTE_LINKEDIN_CLIENT_SECRET'] }}
    refresh_token: {{ env['AIRBYTE_LINKEDIN_REFRESH_TOKEN'] }}
    token_refresh_endpoint: "https://www.linkedin.com/oauth/v2/accessToken"
  requester:
    name: http
    url_base: "https://www.linkedin.com/transparency/api/"
    http_method: "GET"
  streams:
    - name: linkedin-transparency
      retriever:
        requester:
          path: "adLibrary"
          request_parameters:
            q: "SEARCH"
            timeRange.start: "{{ runtime_from_date }}"
            timeRange.end: "{{ runtime_to_date }}"
        record_selector:
          extractor:
            type: DpathExtractor
            field_path:
              - data
      transformations:
        - type: AddFields
          fields:
            - path:
                - effective_from
              value: "{{ now_utc }}"
      schema:
        properties:
          account_id:
            type: ["null", "string"]
          campaign_id:
            type: ["null", "string"]
          ad_creative_id:
            type: ["null", "string"]
          activity_date:
            type: ["null", "string"]
          region:
            type: ["null", "string"]
          spend:
            type: ["null", "number"]
          impressions:
            type: ["null", "integer"]
          clicks:
            type: ["null", "integer"]
