{
  "sourceDefinitionId": "778daa7c-feaf-4db6-96f3-70fd645acc77",
  "workspaceId": "{{ env['AIRBYTE_WORKSPACE_ID'] }}",
  "name": "Meta Ads Incremental",
  "connectionConfiguration": {
    "account_ids": [
      "{{ env['AIRBYTE_META_ACCOUNT_ID'] }}"
    ],
    "credentials": {
      "auth_type": "Service",
      "access_token": "{{ env['AIRBYTE_META_ACCESS_TOKEN'] }}"
    },
    "page_size": 100,
    "start_date": "{{ env.get('AIRBYTE_META_START_DATE', '2023-01-01T00:00:00Z') }}",
    "insights_lookback_window": {{ env.get('AIRBYTE_META_INSIGHTS_LOOKBACK_DAYS', 3) }},
    "include_deleted": false,
    "level": "ad",
    "attribution_window": "default",
    "action_report_time": "conversion",
    "report_interval": "daily",
    "fetch_thumbnail_images": false,
    "custom_insights_fields": ["impressions", "reach", "clicks", "spend", "cpc", "cpm", "actions"],
    "window_in_days": {{ env.get('AIRBYTE_META_ATTRIBUTION_WINDOW_DAYS', 30) }}
  },
  "streams": [
    {
      "name": "ad_insights",
      "syncMode": "incremental",
      "cursorField": [
        "date_start"
      ],
      "primaryKey": [
        [
          "ad_id"
        ],
        [
          "date_start"
        ]
      ],
      "destinationSyncMode": "append_dedup"
    },
    {
      "name": "campaigns",
      "syncMode": "incremental",
      "cursorField": [
        "updated_time"
      ],
      "primaryKey": [
        [
          "id"
        ]
      ],
      "destinationSyncMode": "append_dedup"
    },
    {
      "name": "adsets",
      "syncMode": "incremental",
      "cursorField": [
        "updated_time"
      ],
      "primaryKey": [
        [
          "id"
        ]
      ],
      "destinationSyncMode": "append_dedup"
    },
    {
      "name": "ads",
      "syncMode": "incremental",
      "cursorField": [
        "updated_time"
      ],
      "primaryKey": [
        [
          "id"
        ]
      ],
      "destinationSyncMode": "append_dedup"
    }
  ]
}
