# Stub connector configuration for TikTok Ads transparency data
# Uses the HTTP source against the TikTok Commercial Content Library export.
sourceDefinitionId: 0eb38cfb-7dce-4b03-8a5d-74ac8605e885  # Airbyte HTTP API source
workspaceId: <replace-with-workspace-uuid>
name: "TikTok Transparency (Stub)"
connectionConfiguration:
  provider:
    auth_type: api_key
    api_token: {{ secrets_manager.tiktok_transparency_token }}
  requester:
    name: http
    url_base: "https://ads.tiktok.com/marketing_api/v1/"
    http_method: "GET"
  streams:
    - name: tiktok-transparency
      retriever:
        requester:
          path: "open_api/v1.2/creative/transparent_ads"
          request_parameters:
            advertiser_id: <advertiser-id>
            start_date: "{{ runtime_from_date }}"
            end_date: "{{ runtime_to_date }}"
        record_selector:
          extractor:
            type: DpathExtractor
            field_path:
              - data
              - list
      transformations:
        - type: AddFields
          fields:
            - path:
                - effective_from
              value: "{{ now_utc }}"
      schema:
        properties:
          advertiser_id:
            type: ["null", "string"]
          campaign_id:
            type: ["null", "string"]
          ad_group_id:
            type: ["null", "string"]
          ad_creative_id:
            type: ["null", "string"]
          report_date:
            type: ["null", "string"]
          region:
            type: ["null", "string"]
          spend:
            type: ["null", "number"]
          impressions:
            type: ["null", "integer"]
          clicks:
            type: ["null", "integer"]
