"""Demo adapter serving curated datasets for showcase tenants."""

from __future__ import annotations

from copy import deepcopy
from typing import Any, Mapping

from django.utils import timezone

from .base import AdapterInterface, MetricsAdapter, get_default_interfaces

DEMO_DATASETS: Mapping[str, Mapping[str, Any]] = {
    "bank-of-jamaica": {
        "label": "Bank of Jamaica",
        "payload": {
            "campaign": {
                "summary": {
                    "currency": "JMD",
                    "totalSpend": 4200000,
                    "totalImpressions": 1850000,
                    "totalClicks": 86000,
                    "totalConversions": 5400,
                    "averageRoas": 4.2,
                },
                "trend": [
                    {
                        "date": "2024-09-01",
                        "spend": 780000,
                        "conversions": 980,
                        "clicks": 16200,
                        "impressions": 310000,
                    },
                    {
                        "date": "2024-09-02",
                        "spend": 690000,
                        "conversions": 910,
                        "clicks": 15400,
                        "impressions": 295000,
                    },
                    {
                        "date": "2024-09-03",
                        "spend": 640000,
                        "conversions": 870,
                        "clicks": 14950,
                        "impressions": 288000,
                    },
                ],
                "rows": [
                    {
                        "id": "boj_fx_awareness",
                        "name": "FX Market Awareness",
                        "platform": "Meta",
                        "status": "Active",
                        "parish": "Kingston",
                        "spend": 1200000,
                        "impressions": 540000,
                        "clicks": 24500,
                        "conversions": 1600,
                        "roas": 3.9,
                        "ctr": 0.045,
                        "cpc": 49.0,
                        "cpm": 222.0,
                        "startDate": "2024-08-01",
                        "endDate": "2024-09-30",
                    },
                    {
                        "id": "boj_policy_updates",
                        "name": "Policy Update Series",
                        "platform": "Google Ads",
                        "status": "Active",
                        "parish": "St Andrew",
                        "spend": 980000,
                        "impressions": 460000,
                        "clicks": 22100,
                        "conversions": 1420,
                        "roas": 4.5,
                        "ctr": 0.048,
                        "cpc": 44.4,
                        "cpm": 213.0,
                        "startDate": "2024-08-10",
                        "endDate": "2024-09-28",
                    },
                    {
                        "id": "boj_digital_payments",
                        "name": "Digital Payments Launch",
                        "platform": "TikTok",
                        "status": "Learning",
                        "parish": "St James",
                        "spend": 880000,
                        "impressions": 410000,
                        "clicks": 18900,
                        "conversions": 1350,
                        "roas": 4.1,
                        "ctr": 0.046,
                        "cpc": 46.6,
                        "cpm": 214.6,
                        "startDate": "2024-08-18",
                        "endDate": "2024-10-05",
                    },
                ],
            },
            "creative": [
                {
                    "id": "boj_fx_video",
                    "name": "FX Explainer Video",
                    "campaignId": "boj_fx_awareness",
                    "campaignName": "FX Market Awareness",
                    "platform": "Meta",
                    "parish": "Kingston",
                    "spend": 420000,
                    "impressions": 210000,
                    "clicks": 10200,
                    "conversions": 680,
                    "roas": 3.6,
                    "ctr": 0.0486,
                },
                {
                    "id": "boj_policy_search",
                    "name": "Policy Hub Search",
                    "campaignId": "boj_policy_updates",
                    "campaignName": "Policy Update Series",
                    "platform": "Google Ads",
                    "parish": "St Andrew",
                    "spend": 360000,
                    "impressions": 176000,
                    "clicks": 8600,
                    "conversions": 540,
                    "roas": 4.2,
                    "ctr": 0.0489,
                },
            ],
            "budget": [
                {
                    "id": "boj_fx_awareness_budget",
                    "campaignName": "FX Market Awareness",
                    "parishes": ["Kingston", "St Andrew"],
                    "monthlyBudget": 1500000,
                    "spendToDate": 1200000,
                    "projectedSpend": 1480000,
                    "pacingPercent": 0.99,
                    "startDate": "2024-08-01",
                    "endDate": "2024-09-30",
                },
                {
                    "id": "boj_digital_payments_budget",
                    "campaignName": "Digital Payments Launch",
                    "parishes": ["St James", "Manchester"],
                    "monthlyBudget": 1200000,
                    "spendToDate": 880000,
                    "projectedSpend": 1185000,
                    "pacingPercent": 0.95,
                    "startDate": "2024-08-15",
                    "endDate": "2024-10-05",
                },
            ],
            "parish": [
                {
                    "parish": "Kingston",
                    "spend": 1500000,
                    "impressions": 720000,
                    "clicks": 31800,
                    "conversions": 2050,
                    "roas": 4.0,
                    "campaignCount": 2,
                    "currency": "JMD",
                },
                {
                    "parish": "St Andrew",
                    "spend": 1100000,
                    "impressions": 520000,
                    "clicks": 23800,
                    "conversions": 1580,
                    "roas": 4.4,
                    "campaignCount": 2,
                    "currency": "JMD",
                },
                {
                    "parish": "St James",
                    "spend": 800000,
                    "impressions": 410000,
                    "clicks": 18900,
                    "conversions": 1350,
                    "roas": 4.1,
                    "campaignCount": 1,
                    "currency": "JMD",
                },
            ],
        },
    },
    "grace-kennedy": {
        "label": "GraceKennedy",
        "payload": {
            "campaign": {
                "summary": {
                    "currency": "USD",
                    "totalSpend": 310000,
                    "totalImpressions": 1450000,
                    "totalClicks": 92000,
                    "totalConversions": 7200,
                    "averageRoas": 5.1,
                },
                "trend": [
                    {
                        "date": "2024-09-01",
                        "spend": 98000,
                        "conversions": 2300,
                        "clicks": 31200,
                        "impressions": 480000,
                    },
                    {
                        "date": "2024-09-02",
                        "spend": 102000,
                        "conversions": 2400,
                        "clicks": 30500,
                        "impressions": 520000,
                    },
                    {
                        "date": "2024-09-03",
                        "spend": 110000,
                        "conversions": 2500,
                        "clicks": 30300,
                        "impressions": 450000,
                    },
                ],
                "rows": [
                    {
                        "id": "gk_foods_autumn",
                        "name": "Grace Foods Autumn Push",
                        "platform": "Meta",
                        "status": "Active",
                        "parish": "St Catherine",
                        "spend": 150000,
                        "impressions": 620000,
                        "clicks": 41000,
                        "conversions": 3200,
                        "roas": 4.7,
                        "ctr": 0.066,
                        "cpc": 3.65,
                        "cpm": 242.0,
                        "startDate": "2024-08-12",
                        "endDate": "2024-10-15",
                    },
                    {
                        "id": "gk_financial_services",
                        "name": "GK Money Services",
                        "platform": "Google Ads",
                        "status": "Active",
                        "parish": "Kingston",
                        "spend": 90000,
                        "impressions": 420000,
                        "clicks": 29500,
                        "conversions": 2100,
                        "roas": 5.6,
                        "ctr": 0.07,
                        "cpc": 3.05,
                        "cpm": 214.0,
                        "startDate": "2024-08-01",
                        "endDate": "2024-09-30",
                    },
                    {
                        "id": "gk_remittances",
                        "name": "Western Union Remittances",
                        "platform": "TikTok",
                        "status": "Active",
                        "parish": "St James",
                        "spend": 70000,
                        "impressions": 410000,
                        "clicks": 21500,
                        "conversions": 1900,
                        "roas": 5.1,
                        "ctr": 0.052,
                        "cpc": 3.25,
                        "cpm": 170.7,
                        "startDate": "2024-08-20",
                        "endDate": "2024-10-01",
                    },
                ],
            },
            "creative": [
                {
                    "id": "gk_autumn_recipe",
                    "name": "Autumn Recipe Series",
                    "campaignId": "gk_foods_autumn",
                    "campaignName": "Grace Foods Autumn Push",
                    "platform": "Meta",
                    "parish": "St Catherine",
                    "spend": 64000,
                    "impressions": 280000,
                    "clicks": 18600,
                    "conversions": 1340,
                    "roas": 4.3,
                    "ctr": 0.066,
                },
                {
                    "id": "gk_money_search",
                    "name": "Money Services Search",
                    "campaignId": "gk_financial_services",
                    "campaignName": "GK Money Services",
                    "platform": "Google Ads",
                    "parish": "Kingston",
                    "spend": 42000,
                    "impressions": 190000,
                    "clicks": 14100,
                    "conversions": 980,
                    "roas": 5.2,
                    "ctr": 0.074,
                },
            ],
            "budget": [
                {
                    "id": "gk_foods_budget",
                    "campaignName": "Grace Foods Autumn Push",
                    "parishes": ["St Catherine", "Clarendon"],
                    "monthlyBudget": 180000,
                    "spendToDate": 150000,
                    "projectedSpend": 176000,
                    "pacingPercent": 0.98,
                    "startDate": "2024-08-12",
                    "endDate": "2024-10-15",
                },
                {
                    "id": "gk_money_budget",
                    "campaignName": "GK Money Services",
                    "parishes": ["Kingston", "St Andrew"],
                    "monthlyBudget": 120000,
                    "spendToDate": 90000,
                    "projectedSpend": 118000,
                    "pacingPercent": 0.98,
                    "startDate": "2024-08-01",
                    "endDate": "2024-09-30",
                },
            ],
            "parish": [
                {
                    "parish": "St Catherine",
                    "spend": 160000,
                    "impressions": 650000,
                    "clicks": 43000,
                    "conversions": 3300,
                    "roas": 4.9,
                    "campaignCount": 2,
                    "currency": "USD",
                },
                {
                    "parish": "Kingston",
                    "spend": 90000,
                    "impressions": 420000,
                    "clicks": 29500,
                    "conversions": 2100,
                    "roas": 5.6,
                    "campaignCount": 1,
                    "currency": "USD",
                },
                {
                    "parish": "St James",
                    "spend": 60000,
                    "impressions": 380000,
                    "clicks": 19500,
                    "conversions": 1800,
                    "roas": 4.9,
                    "campaignCount": 1,
                    "currency": "USD",
                },
            ],
        },
    },
    "jdic": {
        "label": "JDIC",
        "payload": {
            "campaign": {
                "summary": {
                    "currency": "JMD",
                    "totalSpend": 1800000,
                    "totalImpressions": 920000,
                    "totalClicks": 51000,
                    "totalConversions": 3100,
                    "averageRoas": 3.7,
                },
                "trend": [
                    {
                        "date": "2024-09-01",
                        "spend": 320000,
                        "conversions": 520,
                        "clicks": 9200,
                        "impressions": 160000,
                    },
                    {
                        "date": "2024-09-02",
                        "spend": 290000,
                        "conversions": 500,
                        "clicks": 8900,
                        "impressions": 150000,
                    },
                    {
                        "date": "2024-09-03",
                        "spend": 310000,
                        "conversions": 540,
                        "clicks": 9300,
                        "impressions": 155000,
                    },
                ],
                "rows": [
                    {
                        "id": "jdic_depositor_protection",
                        "name": "Depositor Protection",
                        "platform": "Meta",
                        "status": "Active",
                        "parish": "Kingston",
                        "spend": 620000,
                        "impressions": 320000,
                        "clicks": 17800,
                        "conversions": 1050,
                        "roas": 3.4,
                        "ctr": 0.055,
                        "cpc": 34.8,
                        "cpm": 193.7,
                        "startDate": "2024-08-05",
                        "endDate": "2024-09-30",
                    },
                    {
                        "id": "jdic_fdic_comparison",
                        "name": "FDIC Comparison",
                        "platform": "Google Ads",
                        "status": "Active",
                        "parish": "St Andrew",
                        "spend": 560000,
                        "impressions": 280000,
                        "clicks": 17200,
                        "conversions": 980,
                        "roas": 3.9,
                        "ctr": 0.061,
                        "cpc": 32.6,
                        "cpm": 200.0,
                        "startDate": "2024-08-10",
                        "endDate": "2024-09-28",
                    },
                    {
                        "id": "jdic_youth_finance",
                        "name": "Youth Financial Literacy",
                        "platform": "TikTok",
                        "status": "Active",
                        "parish": "Manchester",
                        "spend": 420000,
                        "impressions": 320000,
                        "clicks": 16000,
                        "conversions": 1070,
                        "roas": 3.8,
                        "ctr": 0.05,
                        "cpc": 26.3,
                        "cpm": 131.3,
                        "startDate": "2024-08-15",
                        "endDate": "2024-09-30",
                    },
                ],
            },
            "creative": [
                {
                    "id": "jdic_depositor_video",
                    "name": "Depositor Video Story",
                    "campaignId": "jdic_depositor_protection",
                    "campaignName": "Depositor Protection",
                    "platform": "Meta",
                    "parish": "Kingston",
                    "spend": 240000,
                    "impressions": 140000,
                    "clicks": 7800,
                    "conversions": 480,
                    "roas": 3.3,
                    "ctr": 0.055,
                },
                {
                    "id": "jdic_youth_tiktok",
                    "name": "Youth Finance Tips",
                    "campaignId": "jdic_youth_finance",
                    "campaignName": "Youth Financial Literacy",
                    "platform": "TikTok",
                    "parish": "Manchester",
                    "spend": 180000,
                    "impressions": 135000,
                    "clicks": 6500,
                    "conversions": 420,
                    "roas": 3.6,
                    "ctr": 0.048,
                },
            ],
            "budget": [
                {
                    "id": "jdic_depositor_budget",
                    "campaignName": "Depositor Protection",
                    "parishes": ["Kingston", "St Andrew"],
                    "monthlyBudget": 750000,
                    "spendToDate": 620000,
                    "projectedSpend": 732000,
                    "pacingPercent": 0.98,
                    "startDate": "2024-08-05",
                    "endDate": "2024-09-30",
                },
                {
                    "id": "jdic_youth_budget",
                    "campaignName": "Youth Financial Literacy",
                    "parishes": ["Manchester", "St Elizabeth"],
                    "monthlyBudget": 500000,
                    "spendToDate": 420000,
                    "projectedSpend": 498000,
                    "pacingPercent": 0.996,
                    "startDate": "2024-08-15",
                    "endDate": "2024-09-30",
                },
            ],
            "parish": [
                {
                    "parish": "Kingston",
                    "spend": 630000,
                    "impressions": 330000,
                    "clicks": 18100,
                    "conversions": 1080,
                    "roas": 3.5,
                    "campaignCount": 2,
                    "currency": "JMD",
                },
                {
                    "parish": "St Andrew",
                    "spend": 560000,
                    "impressions": 285000,
                    "clicks": 17500,
                    "conversions": 1000,
                    "roas": 3.9,
                    "campaignCount": 1,
                    "currency": "JMD",
                },
                {
                    "parish": "Manchester",
                    "spend": 420000,
                    "impressions": 320000,
                    "clicks": 16000,
                    "conversions": 1070,
                    "roas": 3.8,
                    "campaignCount": 1,
                    "currency": "JMD",
                },
            ],
        },
    },
}

DEFAULT_DEMO_TENANT = "bank-of-jamaica"


class DemoAdapter(MetricsAdapter):
    """Serve curated demo datasets for showcase tenants."""

    key = "demo"
    name = "Demo Tenants"
    description = "Curated sample data for showcase tenants."
    interfaces: tuple[AdapterInterface, ...] = get_default_interfaces()

    def metadata(self) -> dict[str, Any]:
        meta = super().metadata()
        meta["options"] = {
            "demo_tenants": [
                {"id": slug, "label": dataset["label"]}
                for slug, dataset in DEMO_DATASETS.items()
            ]
        }
        return meta

    def fetch_metrics(
        self,
        *,
        tenant_id: str,
        options: Mapping[str, Any] | None = None,
    ) -> Mapping[str, Any]:
        slug = (
            str(options.get("demo_tenant"))  # type: ignore[call-arg]
            if options and "demo_tenant" in options
            else DEFAULT_DEMO_TENANT
        )
        dataset = DEMO_DATASETS.get(slug) or DEMO_DATASETS[DEFAULT_DEMO_TENANT]
        payload = deepcopy(dataset["payload"])
        payload.setdefault("tenant_id", slug)
        payload.setdefault("tenant_label", dataset["label"])
        payload.setdefault("snapshot_generated_at", timezone.now().isoformat())
        return payload
