version: 2

sources:
  - name: raw
    schema: "{{ var('raw_schema', 'raw') }}"
    description: 'Raw ingested tables from Airbyte'
    tables:
      - name: meta_ads_insights
        description: 'Meta Ads insights pulled from the Marketing API.'
        loaded_at_field: _airbyte_emitted_at
        freshness:
          warn_after: { count: "{{ var('freshness_warn_hours', 2) }}", period: hour }
          error_after: { count: "{{ var('freshness_error_hours', 4) }}", period: hour }
        meta:
          sla_note: 'Hourly metrics syncs 06:00–22:00 America/Jamaica; warn after 2h, error after 4h.'
        columns:
          - name: ad_account_id
            tests:
              - not_null
          - name: date_start
            tests:
              - not_null
          - name: _airbyte_raw_id
            tests:
              - unique
      - name: google_ads_insights
        description: 'Google Ads performance data.'
        loaded_at_field: _airbyte_emitted_at
        freshness:
          warn_after: { count: "{{ var('freshness_warn_hours', 2) }}", period: hour }
          error_after: { count: "{{ var('freshness_error_hours', 4) }}", period: hour }
        meta:
          sla_note: 'Hourly metrics syncs 06:00–22:00 America/Jamaica; warn after 2h, error after 4h.'
        columns:
          - name: customer_id
            tests:
              - not_null
          - name: _airbyte_raw_id
            tests:
              - unique
      - name: linkedin_transparency
        description: 'LinkedIn Ads transparency export (optional).'
        loaded_at_field: _airbyte_emitted_at
        freshness:
          warn_after: { count: 7, period: day }
          error_after: { count: 14, period: day }
        enabled: "{{ var('enable_linkedin', False) }}"
        columns:
          - name: account_id
            tests:
              - not_null:
                  config:
                    enabled: "{{ var('enable_linkedin', False) }}"
      - name: tiktok_transparency
        description: 'TikTok Ads transparency data (optional).'
        loaded_at_field: _airbyte_emitted_at
        freshness:
          warn_after: { count: 7, period: day }
          error_after: { count: 14, period: day }
        enabled: "{{ var('enable_tiktok', False) }}"

models:
  - name: stg_meta_ads
    description: 'Normalized Meta Ads insights with Jamaican geo enrichment.'
    columns:
      - name: tenant_id
        description: 'Tenant identifier for row-level isolation.'
        tests:
          - not_null
      - name: ad_account_id
        tests:
          - not_null
      - name: campaign_id
      - name: date_day
        tests:
          - not_null
  - name: stg_google_ads
    description: 'Normalized Google Ads performance data.'
    columns:
      - name: tenant_id
        description: 'Tenant identifier for row-level isolation.'
        tests:
          - not_null
      - name: ad_account_id
      - name: date_day
        tests:
          - not_null
  - name: stg_linkedin_transparency
    description: 'Optional LinkedIn transparency staging model.'
    columns:
      - name: tenant_id
        description: 'Tenant identifier for row-level isolation.'
        tests:
          - not_null:
              config:
                enabled: "{{ var('enable_linkedin', False) }}"
      - name: ad_account_id
        tests:
          - not_null:
              config:
                enabled: "{{ var('enable_linkedin', False) }}"
  - name: stg_tiktok_transparency
    description: 'Optional TikTok transparency staging model.'
    columns:
      - name: tenant_id
        description: 'Tenant identifier for row-level isolation.'
        tests:
          - not_null:
              config:
                enabled: "{{ var('enable_tiktok', False) }}"
      - name: ad_account_id
        tests:
          - not_null:
              config:
                enabled: "{{ var('enable_tiktok', False) }}"
