version: 2

seeds:
  - name: dim_tenants
    description: "Demo tenants available for deterministic datasets."
    columns:
      - name: tenant_id
        description: "Stable identifier for the demo tenant."
        tests:
          - not_null
          - unique
      - name: tenant_name
        description: "Display name for the demo tenant."
        tests:
          - not_null
      - name: currency
        description: "Currency code used for the demo tenant."
        tests:
          - not_null
      - name: timezone
        description: "Timezone associated with the demo tenant."
        tests:
          - not_null
      - name: snapshot_generated_at
        description: "Timestamp used for freshness banners."
        tests:
          - not_null

  - name: dim_campaigns
    description: "Demo campaign dimension."
    tests:
      - unique_combination_of_columns:
          arguments:
            combination:
              - tenant_id
              - campaign_id
    columns:
      - name: tenant_id
        tests:
          - not_null
      - name: campaign_id
        tests:
          - not_null
      - name: channel
        tests:
          - not_null
      - name: campaign_name
        tests:
          - not_null
      - name: objective
        tests:
          - not_null
      - name: status
        tests:
          - not_null
      - name: start_date
        tests:
          - not_null
      - name: end_date
      - name: parish
        description: "Primary parish attribution for the campaign."

  - name: dim_creatives
    description: "Demo creative dimension for campaign assets."
    tests:
      - unique_combination_of_columns:
          arguments:
            combination:
              - tenant_id
              - creative_id
    columns:
      - name: tenant_id
        tests:
          - not_null
      - name: campaign_id
        tests:
          - not_null
      - name: channel
        tests:
          - not_null
      - name: creative_id
        tests:
          - not_null
      - name: creative_name
        tests:
          - not_null
      - name: creative_type
        tests:
          - not_null

  - name: fact_daily_campaign_metrics
    description: "Daily campaign KPI fact table for demo dashboards."
    tests:
      - unique_combination_of_columns:
          arguments:
            combination:
              - tenant_id
              - date
              - campaign_id
              - channel
    columns:
      - name: date
        tests:
          - not_null
      - name: tenant_id
        tests:
          - not_null
      - name: channel
        tests:
          - not_null
      - name: campaign_id
        tests:
          - not_null
      - name: spend
        tests:
          - not_null
      - name: impressions
        tests:
          - not_null
      - name: clicks
        tests:
          - not_null
      - name: conversions
        tests:
          - not_null
      - name: revenue
        tests:
          - not_null
      - name: roas
        tests:
          - not_null
      - name: snapshot_generated_at
        tests:
          - not_null

  - name: fact_daily_parish_metrics
    description: "Daily parish-level metrics for choropleth heatmaps."
    tests:
      - unique_combination_of_columns:
          arguments:
            combination:
              - tenant_id
              - date
              - channel
              - parish
    columns:
      - name: date
        tests:
          - not_null
      - name: tenant_id
        tests:
          - not_null
      - name: channel
        tests:
          - not_null
      - name: parish
        description: "Parish name or blank when missing attribution."
      - name: spend
        tests:
          - not_null
      - name: impressions
        tests:
          - not_null
      - name: clicks
        tests:
          - not_null
      - name: conversions
        tests:
          - not_null
      - name: revenue
        tests:
          - not_null
      - name: roas
        tests:
          - not_null

  - name: fact_daily_creative_metrics
    description: "Daily creative metrics used by creative performance dashboards."
    tests:
      - unique_combination_of_columns:
          arguments:
            combination:
              - tenant_id
              - date
              - campaign_id
              - creative_id
    columns:
      - name: date
        tests:
          - not_null
      - name: tenant_id
        tests:
          - not_null
      - name: channel
        tests:
          - not_null
      - name: campaign_id
        tests:
          - not_null
      - name: creative_id
        tests:
          - not_null
      - name: creative_type
        tests:
          - not_null
      - name: spend
        tests:
          - not_null
      - name: impressions
        tests:
          - not_null
      - name: clicks
        tests:
          - not_null
      - name: conversions
        tests:
          - not_null
      - name: revenue
        tests:
          - not_null
      - name: roas
        tests:
          - not_null

  - name: plan_monthly_budgets
    description: "Monthly planned budgets for pacing comparisons."
    tests:
      - unique_combination_of_columns:
          arguments:
            combination:
              - tenant_id
              - month
              - campaign_id
    columns:
      - name: month
        tests:
          - not_null
      - name: tenant_id
        tests:
          - not_null
      - name: channel
        tests:
          - not_null
      - name: campaign_id
        tests:
          - not_null
      - name: planned_budget
        tests:
          - not_null
