"""AI image/video generation services for Content Operations.

Mirrors the caption generation flow: a job is created with a redacted prompt,
then processed through an injected provider boundary. The default provider is
disabled so no live render spend happens until a provider is configured.
Generated bytes are stored as tenant-scoped ``MediaAsset`` rows (source
``ai_generated``) with AI lineage; oversized or unsupported output is quarantined
by the storage layer rather than published.
"""

from __future__ import annotations

import hashlib
import json
import logging
import re
from dataclasses import dataclass
from typing import Any
from uuid import UUID

from django.db import transaction

from .assets import ContentOpsAssetStorageError, store_generated_asset_bytes
from .generation import redact_secret_like_text
from .metering import record_ai_usage
from .models import GenerationJob, MediaAsset

logger = logging.getLogger(__name__)

IMAGE_FAILURE_PROVIDER_NOT_CONFIGURED = "image_provider_not_configured"
IMAGE_FAILURE_PROVIDER_ERROR = "image_provider_error"
IMAGE_FAILURE_NO_OUTPUT = "image_no_output"
IMAGE_FAILURE_JOB_MISSING = "image_job_missing"
IMAGE_FAILURE_JOB_CANCELLED = "image_job_cancelled"
IMAGE_FAILURE_JOB_WRONG_TYPE = "image_job_wrong_type"
IMAGE_FAILURE_PROMPT_MISSING = "image_prompt_missing"

IMAGE_PROCESS_STATUS_FAILED = "failed"
IMAGE_PROCESS_STATUS_NOOP = "noop"
IMAGE_PROCESS_STATUS_SUCCEEDED = "succeeded"

DEFAULT_IMAGE_COUNT = 1
MAX_IMAGE_COUNT = 4
DEFAULT_IMAGE_SIZE = "1024x1024"
_SIZE_RE = re.compile(r"^\d{3,4}x\d{3,4}$")


@dataclass(frozen=True)
class ImageGenerationProcessResult:
    status: str
    job_id: str = ""
    asset_ids: tuple[str, ...] = ()
    available_count: int = 0
    quarantined_count: int = 0
    failure_code: str = ""
    failure_detail_safe: str = ""

    def as_dict(self) -> dict[str, Any]:
        return {
            "status": self.status,
            "job_id": self.job_id,
            "asset_ids": list(self.asset_ids),
            "available_count": self.available_count,
            "quarantined_count": self.quarantined_count,
            "failure_code": self.failure_code,
            "failure_detail_safe": self.failure_detail_safe,
        }


class ImageGenerationError(RuntimeError):
    """Client-safe image generation error."""

    def __init__(self, *, code: str, detail_safe: str) -> None:
        super().__init__(code)
        self.code = code
        self.detail_safe = detail_safe


class DisabledImageGenerationProvider:
    """Default provider boundary that prevents accidental live render spend."""

    def is_enabled(self) -> bool:
        return False

    def generate(self, payload: dict[str, Any]) -> list:  # noqa: ARG002
        raise ImageGenerationError(
            code=IMAGE_FAILURE_PROVIDER_NOT_CONFIGURED,
            detail_safe="Image generation provider is not configured.",
        )


def normalize_image_count(value: Any = None) -> int:
    if value in (None, ""):
        return DEFAULT_IMAGE_COUNT
    try:
        count = int(value)
    except (TypeError, ValueError):
        return DEFAULT_IMAGE_COUNT
    return max(1, min(count, MAX_IMAGE_COUNT))


def normalize_image_size(value: Any = None) -> str:
    candidate = str(value or "").strip().lower()
    return candidate if _SIZE_RE.match(candidate) else DEFAULT_IMAGE_SIZE


def create_image_generation_job(
    *,
    tenant,
    workspace,
    prompt: str,
    brief=None,
    agent=None,
    count: Any = None,
    size: str = "",
    user=None,
) -> GenerationJob:
    """Create a queued image generation job with a redacted prompt."""

    if workspace.tenant_id != tenant.id:
        raise ValueError("image_workspace_invalid")
    if brief is not None and (
        brief.tenant_id != tenant.id or brief.workspace_id != workspace.id
    ):
        raise ValueError("image_brief_invalid")
    if agent is not None and (
        agent.tenant_id != tenant.id or agent.workspace_id != workspace.id
    ):
        raise ValueError("image_agent_invalid")
    redacted_prompt = redact_secret_like_text(str(prompt or "")).strip()
    if not redacted_prompt:
        raise ValueError(IMAGE_FAILURE_PROMPT_MISSING)
    normalized_count = normalize_image_count(count)
    normalized_size = normalize_image_size(size)
    policy_result = {
        "count": normalized_count,
        "size": normalized_size,
        "prompt": redacted_prompt[:2000],
        "agent_id": str(agent.id) if agent is not None else "",
        "region": agent.region if agent is not None else "",
        "locale": agent.locale if agent is not None else "",
    }
    prompt_summary = redact_secret_like_text(
        f"Image generation: count={normalized_count}; size={normalized_size}; "
        f"prompt={redacted_prompt[:240]}"
    )[:1000]
    return GenerationJob.all_objects.create(
        tenant=tenant,
        workspace=workspace,
        brief=brief,
        regional_agent_profile=agent,
        job_type=GenerationJob.TYPE_GRAPHIC_BATCH,
        provider="disabled",
        model_name="",
        status=GenerationJob.STATUS_QUEUED,
        input_fingerprint=_fingerprint(policy_result),
        redacted_prompt_summary=prompt_summary,
        prompt_policy_result=policy_result,
        result_summary={},
        created_by=user,
    )


def process_content_image_generation_job(
    job_id: str | UUID,
    provider=None,
) -> ImageGenerationProcessResult:
    """Run one image generation job through an injected provider boundary."""

    existing = _load_image_job(job_id)
    if existing is None:
        return ImageGenerationProcessResult(
            status=IMAGE_PROCESS_STATUS_NOOP,
            failure_code=IMAGE_FAILURE_JOB_MISSING,
            failure_detail_safe="Generation job does not exist.",
        )
    if existing.status == GenerationJob.STATUS_CANCELLED:
        return ImageGenerationProcessResult(
            status=IMAGE_PROCESS_STATUS_NOOP,
            job_id=str(existing.id),
            failure_code=IMAGE_FAILURE_JOB_CANCELLED,
            failure_detail_safe="Generation job was cancelled.",
        )
    if existing.status == GenerationJob.STATUS_SUCCEEDED:
        summary = existing.result_summary or {}
        asset_ids = tuple(str(value) for value in summary.get("asset_ids", []))
        return ImageGenerationProcessResult(
            status=IMAGE_PROCESS_STATUS_NOOP,
            job_id=str(existing.id),
            asset_ids=asset_ids,
            available_count=int(summary.get("available_count", 0)),
            quarantined_count=int(summary.get("quarantined_count", 0)),
        )
    if existing.job_type != GenerationJob.TYPE_GRAPHIC_BATCH:
        return _mark_image_job_failed(
            job_id=existing.id,
            code=IMAGE_FAILURE_JOB_WRONG_TYPE,
            detail="Generation job is not an image job.",
        )

    with transaction.atomic():
        job = _locked_image_job(job_id)
        if job is None:
            return ImageGenerationProcessResult(
                status=IMAGE_PROCESS_STATUS_NOOP,
                failure_code=IMAGE_FAILURE_JOB_MISSING,
                failure_detail_safe="Generation job does not exist.",
            )
        if job.status in {
            GenerationJob.STATUS_CANCELLED,
            GenerationJob.STATUS_SUCCEEDED,
        }:
            return ImageGenerationProcessResult(
                status=IMAGE_PROCESS_STATUS_NOOP,
                job_id=str(job.id),
            )
        job.status = GenerationJob.STATUS_RUNNING
        job.error_code = ""
        job.save(update_fields=["status", "error_code", "updated_at"])
        payload = _image_payload_from_job(job)

    selected_provider = provider or _resolve_image_provider(existing.tenant)
    generation_error: ImageGenerationError | None = None
    images: list = []
    try:
        images = list(selected_provider.generate(payload))
    except ImageGenerationError as exc:
        generation_error = exc

    _record_image_usage(job=existing, provider=selected_provider)

    if generation_error is not None:
        return _mark_image_job_failed(
            job_id=existing.id,
            code=generation_error.code,
            detail=generation_error.detail_safe,
        )
    if not images:
        return _mark_image_job_failed(
            job_id=existing.id,
            code=IMAGE_FAILURE_NO_OUTPUT,
            detail="Image provider returned no media.",
        )

    return _store_generated_images(
        job_id=existing.id,
        images=images,
        provider=selected_provider,
        payload=payload,
    )


def _store_generated_images(
    *,
    job_id: str | UUID,
    images: list,
    provider: Any,
    payload: dict[str, Any],
) -> ImageGenerationProcessResult:
    usage = getattr(provider, "last_usage", None)
    provider_name = str(getattr(usage, "provider", "") or getattr(provider, "provider_name", ""))
    model_name = str(getattr(usage, "model", "") or getattr(provider, "model", "") or "")
    alt_text = str(payload.get("prompt") or "")[:1000]

    with transaction.atomic():
        job = _locked_image_job(job_id)
        if job is None:
            return ImageGenerationProcessResult(
                status=IMAGE_PROCESS_STATUS_NOOP,
                failure_code=IMAGE_FAILURE_JOB_MISSING,
                failure_detail_safe="Generation job does not exist.",
            )
        if job.status == GenerationJob.STATUS_CANCELLED:
            return ImageGenerationProcessResult(
                status=IMAGE_PROCESS_STATUS_NOOP,
                job_id=str(job.id),
                failure_code=IMAGE_FAILURE_JOB_CANCELLED,
                failure_detail_safe="Generation job was cancelled.",
            )

        asset_ids: list[str] = []
        available = 0
        quarantined = 0
        for index, image in enumerate(images):
            content = getattr(image, "content", b"") or b""
            if not content:
                continue
            lineage = {
                "provider": provider_name,
                "model": model_name,
                "prompt_fingerprint": job.input_fingerprint,
                "seed": str(getattr(image, "seed", "") or ""),
                "size": payload.get("size", ""),
                "generation_job_id": str(job.id),
                "index": index,
            }
            try:
                asset = store_generated_asset_bytes(
                    tenant=job.tenant,
                    workspace=job.workspace,
                    content=content,
                    mime_type=str(getattr(image, "mime_type", "") or "image/png"),
                    alt_text=alt_text,
                    ai_lineage=lineage,
                    width=getattr(image, "width", None),
                    height=getattr(image, "height", None),
                )
            except ContentOpsAssetStorageError:
                logger.warning("Failed to store generated asset for job %s", job.id)
                continue
            asset_ids.append(str(asset.id))
            if asset.status == MediaAsset.STATUS_AVAILABLE:
                available += 1
            else:
                quarantined += 1

        if not asset_ids:
            return _mark_locked_image_failed(
                job=job,
                code=IMAGE_FAILURE_NO_OUTPUT,
                detail="No generated media could be stored.",
            )

        job.status = GenerationJob.STATUS_SUCCEEDED
        job.error_code = ""
        job.result_summary = {
            "asset_ids": asset_ids,
            "available_count": available,
            "quarantined_count": quarantined,
            "image_count": len(images),
        }
        job.save(update_fields=["status", "error_code", "result_summary", "updated_at"])
        return ImageGenerationProcessResult(
            status=IMAGE_PROCESS_STATUS_SUCCEEDED,
            job_id=str(job.id),
            asset_ids=tuple(asset_ids),
            available_count=available,
            quarantined_count=quarantined,
        )


def _resolve_image_provider(tenant):
    from .providers import get_image_provider

    return get_image_provider(tenant=tenant)


def _record_image_usage(*, job: GenerationJob, provider: Any) -> None:
    usage = getattr(provider, "last_usage", None)
    if usage is None:
        return
    try:
        record_ai_usage(job=job, usage=usage)
    except Exception:  # noqa: BLE001 - metering must never break generation
        logger.warning("Failed to record AI image usage for job %s", job.id, exc_info=True)


def _image_payload_from_job(job: GenerationJob) -> dict[str, Any]:
    policy = job.prompt_policy_result or {}
    payload: dict[str, Any] = {
        "prompt": str(policy.get("prompt") or ""),
        "count": normalize_image_count(policy.get("count")),
        "size": normalize_image_size(policy.get("size")),
    }
    agent = job.regional_agent_profile
    if agent is not None:
        payload["agent"] = {
            "region": agent.region,
            "locale": agent.locale,
            "language": agent.language,
        }
    return payload


def _mark_image_job_failed(
    *, job_id: str | UUID, code: str, detail: str
) -> ImageGenerationProcessResult:
    with transaction.atomic():
        job = _locked_image_job(job_id)
        if job is None:
            return ImageGenerationProcessResult(
                status=IMAGE_PROCESS_STATUS_NOOP,
                failure_code=IMAGE_FAILURE_JOB_MISSING,
                failure_detail_safe="Generation job does not exist.",
            )
        return _mark_locked_image_failed(job=job, code=code, detail=detail)


def _mark_locked_image_failed(
    *, job: GenerationJob, code: str, detail: str
) -> ImageGenerationProcessResult:
    safe_detail = redact_secret_like_text(str(detail or "Image generation failed."))[:500]
    job.status = GenerationJob.STATUS_FAILED
    job.error_code = code
    job.result_summary = {"failure_code": code, "failure_detail_safe": safe_detail}
    job.save(update_fields=["status", "error_code", "result_summary", "updated_at"])
    return ImageGenerationProcessResult(
        status=IMAGE_PROCESS_STATUS_FAILED,
        job_id=str(job.id),
        failure_code=code,
        failure_detail_safe=safe_detail,
    )


def _load_image_job(job_id: str | UUID) -> GenerationJob | None:
    return (
        GenerationJob.all_objects.select_related(
            "tenant", "workspace", "brief", "regional_agent_profile"
        )
        .filter(id=job_id)
        .first()
    )


def _locked_image_job(job_id: str | UUID) -> GenerationJob | None:
    return (
        GenerationJob.all_objects.select_for_update()
        .select_related("tenant", "workspace", "brief", "regional_agent_profile")
        .filter(id=job_id)
        .first()
    )


def _fingerprint(payload: dict[str, Any]) -> str:
    rendered = json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str)
    return hashlib.sha256(rendered.encode("utf-8")).hexdigest()


__all__ = [
    "DEFAULT_IMAGE_SIZE",
    "IMAGE_FAILURE_JOB_WRONG_TYPE",
    "IMAGE_FAILURE_NO_OUTPUT",
    "IMAGE_FAILURE_PROMPT_MISSING",
    "IMAGE_FAILURE_PROVIDER_ERROR",
    "IMAGE_FAILURE_PROVIDER_NOT_CONFIGURED",
    "IMAGE_PROCESS_STATUS_FAILED",
    "IMAGE_PROCESS_STATUS_NOOP",
    "IMAGE_PROCESS_STATUS_SUCCEEDED",
    "MAX_IMAGE_COUNT",
    "DisabledImageGenerationProvider",
    "ImageGenerationError",
    "ImageGenerationProcessResult",
    "create_image_generation_job",
    "normalize_image_count",
    "normalize_image_size",
    "process_content_image_generation_job",
]
