name: QA
on: [push, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.56.0-noble
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci
      - run: npx playwright install chromium
      - name: Run mocked E2E (dev)
        env: { MOCK_MODE: 'true', QA_BASE_URL: 'http://127.0.0.1:5173' }
        run: npm test -- --project=chromium-desktop
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with: { name: playwright-report, path: playwright-report, if-no-files-found: ignore }
