name: QA E2E

on:
  pull_request:
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  playwright:
    name: Playwright QA
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: qa
    env:
      MOCK_MODE: "true"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: qa/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('qa/package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm test

      - name: Upload Playwright artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          if-no-files-found: ignore
          path: |
            qa/test-results/**/*
            qa/playwright-report/**/*
